- identity-provider-service/Cargo.toml
- idiss/Cargo.toml
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.toml
- rust-src/aggregate_sig/Cargo.toml
- rust-src/bulletproofs/Cargo.toml
- rust-src/crypto_common/Cargo.toml
- rust-src/crypto_common_derive/Cargo.toml
- rust-src/curve_arithmetic/Cargo.toml
- rust-src/dodis_yampolskiy_prf/Cargo.toml
- rust-src/ecvrf/Cargo.toml
- rust-src/eddsa_ed25519/Cargo.toml
- rust-src/elgamal/Cargo.toml
- rust-src/encrypted_transfers/Cargo.toml
- rust-src/ffi_helpers/Cargo.toml
- rust-src/id/Cargo.toml
- rust-src/keygen_bls/Cargo.toml
- rust-src/pedersen_scheme/Cargo.toml
- rust-src/ps_sig/Cargo.toml
- rust-src/random_oracle/Cargo.toml
- rust-src/sha_2/Cargo.toml
- rust-src/wallet/Cargo.toml
Remove needless license declarations. Only one of license/license-file is needed.
> Cleanup redundant declarations.

- scripts/genesis-tools.Dockerfile
Use the public repositories and public docker images.
> Update genesis dockerfile build for github sources.

- genesis-tools.Jenkinsfiles
- scripts/genesis-tools.Dockerfile
Based on the build pipeline for the base image.
> Add jenkins pipeline for genesis-tools

- identity-provider-service/src/bin/main.rs
Consistency. We return the entire message that we send to the chain.
This will remove some special casing and matches directly the response the identity provider library gives, meaning that there is no need to process the responses.
> Change response format to match other services.

- haskell-src/Concordium/Types/Updates.hs
Fix update types so that they correspond to update queues. This fixes a problem with sequence number tracking.
Revise the UpdateType type to match the structure of the update queues.
This also changes the serialization of update payload for the key update types. It is actually a bit simpler since there is no duplication of tags for the different key updates. The only user of this currently is the desktop wallet where they will update their serialization to match.
> Fix update types so that they correspond to update queues.

- rust-bins/src/bin/client.rs
Make the id-client easier to script with, and fix the output format to match what the concordium-client expects.
- Add flags to disable interactive prompts.
- Change the credential output format to match what concordium-client expects.
> Add more options via command-line for easier scripting.

- haskell-src/Concordium/Utils/Encryption.hs
Return whether an encrypted or decrypted content was parsed.
> Eb encrypt baker keys

- rust-bins/docs/keygen.md
Make documentation correspond to reality for the keygen tool.
> Fix documentation of the keygen tool.

- haskell-src/Concordium/Wasm.hs
Fix serialization of addresses.
> Fix serialization of addresses.

- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Execution.hs
Cleanup comments which no longer make sense.
Delete obsolete comments.
> Remove obsolete comments.

- .github/workflows/build-test.yaml
- README.md
- identity-provider-service/src/bin/main.rs
- idiss/Cargo.lock
- idiss/README.md
- mobile_wallet/src/lib.rs
- rust-bins/Cargo.toml
- rust-bins/src/bin/keygen.rs
- rust-src/crypto_common/Cargo.toml
- rust-src/curve_arithmetic/src/curve_arithmetic.rs
- rust-src/ecvrf/src/proof.rs
- rust-src/elgamal/src/secret.rs
- rust-src/encrypted_transfers/src/proofs/generate_proofs.rs
- rust-src/keygen_bls/Cargo.toml
- rustfmt.toml
Keep abreast of the rust ecosystem.
- Update rust version used in the CI.
- Bump some dependencies which were blocked due to out of date rust compiler version.
> Update rust version to 1.53.

- haskell-src/Concordium/Types/Accounts.hs
Add missing FromJSON instances. They are needed in the tokenomics reporter (and in the future in concordium-client).
Add some missing fromjson instances.
> Add missing FromJSON instances.

- haskell-src/Concordium/Types/Queries.hs
Correct the ToJSON instance of TransactionStatus.
> Fix ToJSON instance of transaction status.

- haskell-src/Concordium/Types.hs
Minor improvement of error message used in the case where an error is thrown due to a memo or registered data being too big. These are thrown by `memoFromBSS` and `registeredDataFromBSS`. 
* The phrasing of the error messages have been changed a little bit.
> Improve error message when memo or registered data is too big

- rust-src/id/src/types.rs
Implement missing instances needed in the rust-sdk.
Derive clone and debug for the type.
> Implement missing clone and debug instances.

- identity-provider-service/Cargo.lock
- mobile_wallet/Cargo.lock
Some dependencies have been removed, but not all lock files have been regenerated leading to constant "Changed files" when doing local development.
Regenerate remaining lock files.
> Remove unused dependencies from Cargo.lock files.

- README.md
- rust-bins/docs/id-client.md
Update and make public the internal documentation for test tools.
> Add documentation for identity layer interactions.

- idiss/Cargo.lock
- idiss/Cargo.toml
- idiss/example.js
- idiss/src/nodejs_exports.rs
Add a version endpoint to the nodejs idiss exports for easier testing.
> Add a version function to libiss for testing.

- CHANGELOG.md
- concordium-base.cabal
- haskell-bins/genesis/Genesis.hs
- haskell-bins/genesis/README.md
- haskell-src/Concordium/Genesis/Data.hs
- haskell-src/Concordium/Genesis/Data/P3.hs
- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Accounts.hs
- haskell-src/Concordium/Types/Execution.hs
- haskell-src/Concordium/Types/ProtocolVersion.hs
- haskell-src/Data/FixedByteString.hs
- haskell-tests/Spec.hs
- haskell-tests/Types/AddressesSpec.hs
Introduce infrastructure for the P3 protocol update. Closes #94 
- Add a new protocol update (P3).
- Introduce auxiliary type to compare addresses by only comparing prefixes.
> Account aliases

- rust-src/Cargo.lock
- rust-src/crypto_common/Cargo.toml
- rust-src/id/src/types.rs
Add a few convenience methods that are needed in the rust sdk.
> Add minor helper types and functions.

- haskell-src/Concordium/Genesis/Data/P4.hs
- haskell-src/Concordium/Types/Execution.hs
- haskell-tests/ConcordiumTests/ID/Types.hs
- haskell-tests/Types/AccountEncryptedAmountSpec.hs
- haskell-tests/Types/AddressesSpec.hs
- haskell-tests/Types/Generators.hs
- haskell-tests/Types/PayloadSerializationSpec.hs
- haskell-tests/Types/RewardTypes.hs
- haskell-tests/Types/TransactionSerializationSpec.hs
- haskell-tests/Types/TransactionSummarySpec.hs
- haskell-tests/Types/UpdatesSpec.hs
Finish refactoring and tests, related to early work on https://github.com/Concordium/concordium-node/issues/212. 
Finish test file `Generators.hs` for generic generators and moved most of the generators there. I have added negative tests for configure baker and configure delegation payloads.
We will need to update the change log at some point regarding delegation, but perhaps a bit early to do so now.
> Delegation

- rust-bins/docs/user-cli.md
Updated user_cli readme after testing tool. 
- Updated the readme to make some aspects clearer for a first time reader. 
- Corrected some typos.
> Updated user_cli readme

- haskell-src/Concordium/ID/Types.hs
- rust-bins/src/bin/identity_provider_cli.rs
- rust-bins/src/bin/user_cli.rs
Polish identity issuance tools a little bit after feedback from @concordium-cl 
Usability improvements.
> Polish the identity provider and user tools after feedback.

- rust-bins/docs/identity-provider-cli.md
IDP must accept user's choice of ars and ar threshold, to make it clearer that this is their responsibility.
> minor addition to readme

- haskell-bins/genesis/Genesis.hs
- haskell-src/Concordium/Types/Parameters.hs
Work on delegation https://github.com/Concordium/concordium-node/issues/212
* Finish printing of genesis data
* Add some documentation
* Fix some warnings 
> Finish genesis data print functionality and some documentation

- rust-bins/docs/user-cli.md
Describe keys that are generated by the user-cli tool.
> Describe keys that are generated by user_cli

- rust-bins/docs/user-cli.md
Add link to documentation of the utils tool for decrypting.
> Add documentation link

- haskell-src/Concordium/ID/Types.hs
Supports https://github.com/Concordium/concordium-node/pull/217
> Implement Hashable for AccountInformation

- rust-src/Cargo.lock
- rust-src/crypto_common/src/impls.rs
- rust-src/eddsa_ed25519/src/eddsa_ed25519.rs
Fixes #116 
Remove the uses of ::new with ::from
This is purely an internal change. No externally visible change is made.
> Remove the use of deprecated functions.

- rust-bins/docs/id-client.md
Minor fixes that came up when following the instructions for generating credentials.
> Minor documentation cleanup

- haskell-src/Concordium/Wasm.hs
Helper functions for dealing with Wasm names. This is leftover from #115 .
Add helper functions.
> Helper functions for dealing with Wasm names.

- haskell-src/Concordium/Types/InvokeContract.hs
Expose return value even if invocation fails, if available.
> Expose return value even in case of failure.

- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
To update the version of the mobile wallet library from 0.9.0 to 0.10.0.
The version of the mobile wallet library has been updated from 0.9.0 to 0.10.0
> Fix version of mobilewallet library.

- rust-src/id/src/types.rs
Add helper functions to generate and check for aliases.
Add `is_alias_of` and `get_alias` functions with corresponding tests.
> Add helper functions to generate and check for aliases.

- rust-bins/wallet-notes/README.md
> Fix links to example files.

- haskell-src/Concordium/Types/Execution.hs
- haskell-src/Concordium/Types/Transactions.hs
Address delegation review comments.
Supports: https://github.com/Concordium/concordium-node/pull/296
- Minor changes to documentation.
> Address delegation review comments.

- mobile_wallet/scripts/android.Jenkinsfile
- mobile_wallet/scripts/ios.Jenkinsfile
Add version to the mobile wallet library build output.
> Add version mobile wallet libs

- .github/workflows/build-test.yaml
- README.md
- haskell-bins/genesis/Genesis.hs
- haskell-src/Concordium/Crypto/ByteStringHelpers.hs
- haskell-src/Concordium/ID/Types.hs
- haskell-src/Concordium/Types/Execution.hs
- haskell-src/Concordium/Types/InvokeContract.hs
- haskell-src/Concordium/Types/Transactions.hs
- haskell-src/Concordium/Types/Updates.hs
- haskell-src/Concordium/Utils.hs
- haskell-src/Concordium/Wasm.hs
- haskell-tests/Generators.hs
- stack.yaml
Mostly applies the changes in the APIs of the dependencies.
Upgrade the toolchain and the dependencies to the latest version.
Upgrades the resolver version to `lts-19.6` and ghc to `9.0.2`.
> Upgrades the resolver version to lts-19.6.

- haskell-src/Concordium/Types/Queries.hs
Fix incorrect misleading documentation of the JSON representation.
No code changes, just format description.
> Fix documentation of the JSON encoding of pending pool changes.

- haskell-src/Concordium/Types/Parameters.hs
Merge release 4.1 bugfixes into main.
The changes here are those in #163 
Closes #162
> Merge 4.1 bugfixes

- mobile_wallet/src/android.rs
To fix the android.rs file that did not build.
A few functions were not imported. Those are now imported.
> Import new functions.

- mobile_wallet/android/mobile_wallet_lib/src/main/java/com/concordium/mobile_wallet_lib/wallet.kt
- mobile_wallet/src/android.rs
To expose the newly introduced functions on Android. 
The functions were not exposed. They are now exposed.
> Expose newly introduced functions on Android.

- idiss/README.md
> Fix leftover Rust version number.

- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
Bump the internal identity provider version after adding failing capabilities.
Bump the internal identity provider.
> Bump idp version to 0.3.0

- mobile_wallet/src/android.rs
To import the function for generating identity recover requests to be used from Android.
Function now imported.
> Import function that should have been imported.

- smart-contracts/wasm-chain-integration/src/utils.rs
Part of https://github.com/Concordium/concordium-rust-smart-contracts
- Added function for generating schemas to use v2 schemas
> Contract error schemas

- identity-provider-service/README.md
To document the recovery endpoint of the internal identity provider.
* README updated.
> Document recovery endpoint.

- rust-bins/docs/identity-provider-cli.md
- rust-bins/docs/user-cli.md
I added some clarifications and corrections to the company identity flow v1.
- aligned wording in both files (recovery-request.json)
- deleted that accounts cannot be recovered
- added last step to user and idp recovery description
> Text corrections for company identities v1

- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-transform/Cargo.toml
upddate concordium-contracts-common to 4.0.0
> Update concordium-contracts-common to 4.0.0

- haskell-src/Concordium/Utils/Encryption.hs
In support of https://github.com/Concordium/concordium-client/issues/170
- Add a JSON parser for encrypted data that takes a custom parser, not relying on the FromJSON instance directly.
- Add a helper "isLikelyEncrypted" method.
> Add ability to provide custom JSON parser when decrypting.

- rust-src/concordium_base/src/base.rs
Smart constructors to help in the rust-sdk.
Add smart constructors for leveragefactor and exchangerate and make use of them.
> Expose some smart constructors.

- haskell-src/Concordium/Types/Parameters.hs
- haskell-src/Concordium/Types/Queries.hs
Add types relevant for new queries.
Should be merged with https://github.com/Concordium/concordium-node/pull/526.
> Introduce types for querying update sequence numbers and pending updates

- rust-src/crypto_common/src/types.rs
- smart-contracts/wasm-chain-integration/Cargo.toml
Add missing serialization instnace.
> Add serialization for Address.

- rust-src/concordium_base/src/base.rs
Add support for protocol version 5 in concordium-base crate.
> Add support for protocol version 5 in concordium-base.

- haskell-src/Concordium/Cost.hs
- haskell-src/Concordium/Types/ProtocolVersion.hs
- haskell-src/Concordium/Wasm.hs
- smart-contracts/rustfmt.toml
- smart-contracts/wasm-chain-integration/benches/v1-host-functions.rs
- smart-contracts/wasm-chain-integration/src/v1/crypto_primitives_tests.rs
- smart-contracts/wasm-chain-integration/src/v1/ffi.rs
- smart-contracts/wasm-chain-integration/src/v1/mod.rs
Implement smart contract queries for account and contract balances and the current exchange rates.
See https://github.com/Concordium/concordium-node/issues/562.
This PR should be merge with https://github.com/Concordium/concordium-node/pull/569
- Extend the invoke operations with the 3 new queries in the smart contract execution engine.
- Add support of smart contract queries predicate provided the protocol version.
> Support smart contract queries in execution engine

- haskell-src/Concordium/Wasm.hs
Add helper needed for some validation in the node.
> Add a helper to get size of a parameter in bytes.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/CHANGELOG.md
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- mobile_wallet/src/lib.rs
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/src/utils.rs
Schemas for events
Add support for schema version 3
> Add schema version 3

- smart-contracts/wasm-chain-integration/src/v1/mod.rs
Part of https://github.com/Concordium/concordium-node/issues/591
> Retain logs through the interrupt for queries.

- rust-bins/wallet-notes/README.md
Fix mobile wallet lib readme :upside_down_face:
> Fix description of to parameter for serialize_token_transfer_parameters

- haskell-src/Concordium/Cost.hs
Fixes https://github.com/Concordium/concordium-node/issues/600
Increase the cost of the exchange rate query.
With this setting the worst execution time seems to be around 0.4s on the i12900. This is good enough.
> Increase cost of exchange the rate query.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- mobile_wallet/src/lib.rs
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-test/Cargo.lock
See [this issue](https://github.com/Concordium/concordium-contracts-common/pull/58#issue-1426856199).
> Update submodule and changed mobile wallet to use VersionedSchema helpers

- .github/workflows/build-test-sources.yaml
- mobile_wallet/src/android.rs
Fix the android build of mobile wallet libraries and add check to CI.
> Fix android

- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- identity-provider-service/src/bin/identity_verifier.rs
Allow creating identities without some attributes.
IDP now filters attributes that are empty string away.
> 0.4.0 IDP removes empty attributes

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-src/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-transform/Cargo.toml
contracts-common version is bumped for release. This just propagates the changes.
> Bump the contracts-common dependency.

- .github/workflows/build-test-sources.yaml
- haskell-src/Concordium/Common/Version.hs
- haskell-src/Concordium/Crypto/EncryptedTransfers.hs
- haskell-src/Concordium/Types/ProtocolVersion/TH.hs
- haskell-src/Concordium/Utils.hs
- haskell-src/Concordium/Utils/Serialization/Put.hs
- haskell-src/Data/FixedByteString.hs
- haskell-tests/Types/AddressesSpec.hs
- haskell-tests/Types/PayloadSerializationSpec.hs
- stack.yaml
Upgrade stackage snapshot to `lts-20.4` and ghc to 9.2.5.
Change `resolver`in `stack.yaml` and fix build errors and warnings.
> Upgrade compiler tooling and libraries.

- haskell-src/Concordium/Types/ProtocolVersion.hs
Add helper function for checking whether the protocol version supports account aliases.
> Add supportsAccountAliases helper

- rust-src/concordium_base/src/cis2_types.rs
Add some convenience methods to use in the RUst SDK related to token amounts.
> Token amount display helpers

- rust-src/concordium_base/src/cis2_types.rs
Use a proper error type since we are exposing this in the SDK.
> Use proper error type for parse failure.

- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Bump changelogs for release of smart contract libraries.
> Bump changelog for release.

- haskell-src/Concordium/Genesis/Data/BaseV1.hs
- haskell-src/Concordium/Genesis/Data/P6.hs
Fix unused imports from premature merge of #320.
Remove unused import statements.
> Fix unused imports.

- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/encrypted_transfers/Cargo.toml
Fix issue introduced by merging #309 
The rand dependency was not specified correctly
> Fix the rand dependency.

- smart-contracts/wasm-chain-integration/benches/wasm.rs
Apply changes from https://github.com/Concordium/concordium-contracts-common/pull/75
Depends on:
- https://github.com/Concordium/concordium-contracts-common/pull/75
- Update dependency 
- Apply changes
> Use new `empty` method and update dependency

- .github/workflows/build-test-smart-contracts.yaml
- .github/workflows/build-test-sources.yaml
It happens too many times that only some lock files are updated when dependencies are updated.
This addition should ensure that the CI catches those cases.
> Ensure Cargo.lock files are up-to-date.

- rust-src/concordium_base/src/cis2_types.rs
Fix CIS2 token event Display implementation.
> Fix CIS2 token Display implementation.

- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- idiss/Cargo.lock
- idiss/Cargo.toml
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-bins/Cargo.toml
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- rust-src/concordium_base/README.md
- rust-src/concordium_base/src/aggregate_sig/mod.rs
- rust-src/concordium_base/src/constants.rs
- rust-src/concordium_base/src/id/mod.rs
- rust-src/concordium_base/src/id/types.rs
- rust-src/concordium_base/src/lib.rs
- rust-src/concordium_base/src/smart_contracts.rs
- rust-src/concordium_base/src/transactions.rs
- rust-src/concordium_base_derive/Cargo.toml
- rust-src/concordium_base_derive/README.md
- rust-src/concordium_base_derive/src/lib.rs
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-test/Cargo.lock
Prepare concordium-base and concordium-base-derive for publication.
Part of #335 
- Set version of packages to 1
- Add top-level documentation.
- Add crate metadata.
> Prepare concordium-base and concordium-base-derive for publication

- rust-src/concordium_base/Cargo.toml
Fix manifest so that concordium_base can be published.
> Fix manifest of the concordium_base library to include src.

- haskell-src/Concordium/GRPC2.hs
incomingAmounts were only set when there were aggregated amounts as well.
> Fix ToProto for incoming amounts.

- .github/workflows/build-test-smart-contracts.yaml
- .github/workflows/build-test-sources.yaml
- rust-src/concordium_base/src/common/serialize.rs
- rust-src/concordium_base/src/common/version.rs
- rust-src/concordium_base/src/curve_arithmetic/secret_value.rs
- rust-src/concordium_base/src/dodis_yampolskiy_prf/secret.rs
- rust-src/concordium_base/src/elgamal/cipher.rs
- rust-src/concordium_base/src/pedersen_commitment/commitment.rs
- rust-src/concordium_base/src/pedersen_commitment/randomness.rs
- rust-src/concordium_base/src/ps_sig/unknown_message.rs
- rust-src/concordium_base/src/transactions.rs
- smart-contracts/wasm-chain-integration/src/v1/mod.rs
- smart-contracts/wasm-transform/src/parse.rs
Since we publish libraries now it is important that the documentation works.
These changes ensure that there are no warnings while generating documentation.
> Lint documentation.

- rust-src/concordium_base/src/base.rs
Move AccountAddressEq to base from the sc testing library. This is needed in the Rust SDK, transaction logger, etc. So it is better to have it one place.
> Move accountaddresseq to base.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/Cargo.toml
Bump version of concordium-base for release.
> Bump version of concordium-base for release.

- mobile_wallet/src/lib.rs
- rust-bins/src/bin/client.rs
- rust-bins/src/bin/user_cli.rs
- rust-bins/src/lib.rs
- rust-src/concordium_base/src/base.rs
- rust-src/key_derivation/src/lib.rs
We need these helpers in some tools related to the new identity projects. Instead of copying these definitions again I decided to move them to a library.
> Consolidate definitions

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/common/types.rs
- rust-src/concordium_base/src/id/types.rs
- rust-src/concordium_base/src/updates.rs
Add some helpers needed in the SDK and various tools.
> Add a few helpers to extract data from credentials.

- smart-contracts/wasm-chain-integration/src/v1/trie/low_level.rs
Reduce the use of unsafe code.
There are no functional changes in this PR, only some unsafe accesses are replaced by accesses that will raise a panic.
> Reduce the use of unsafe code.

- haskell-src/Concordium/Types/Parameters.hs
- haskell-src/Concordium/Types/SeedState.hs
This implements changes to support https://github.com/concordium/concordium-node/issues/699
- Additional constraints associated with `IsConsensusV1`.
> New consensus block execution

- rust-src/concordium_base/src/cis2_types.rs
- rust-src/concordium_base/src/cis4_types.rs
- rust-src/concordium_base/src/web3id/mod.rs
> Misc web3id additions and changes

- haskell-src/Concordium/Types/Queries.hs
Add To/From JSON instance for sequence numbers. 
Needed in the client.
> Add To/FromJSON instance for nextupdatesequencenumbers.

- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-bins/Cargo.toml
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-fuzz/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Bump version of contracts-common and published libraries to prepare for release.
> Bump versions to prepare for release.

- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types/Parameters.hs
- haskell-src/Concordium/Types/Queries.hs
- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- identity-provider-service/html/attribute_form.html
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-bins/Cargo.toml
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- rust-src/concordium_base/src/base.rs
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-fuzz/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Minor revision to group things which always or not together.
> Fix dummy values misc

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.lock
Update submodule link
Update submodule link
> Update submodule link

- rust-src/concordium_base/src/id/sigma_protocols/com_ineq.rs
- rust-src/concordium_base/src/id/sigma_protocols/mod.rs
This pull request adds a Sigma protocol for inequality statements.
Added non-equality Sigma protocol.
> Inequality sigma protocol

- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types/Accounts.hs
- haskell-src/Concordium/Types/Queries.hs
Added the type definition `BakerRewardPeriodInfo` which is the type streamed as a response of `GetBakersRewardPeriod`.
> Update grpc submodule to support GetRewardPeriodInfo.

- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types/Queries.hs
Add the commission rates that apply for the current reward period to the `CurrentPaydayBakerPoolStatus`
> Add a 'CommissionRates' field to 'CurrentPaydayBakerPoolStatus'.

- rust-bins/docs/identity-provider-cli.md
- rust-bins/docs/user-cli.md
Added sources to the required files so that it is more clear how to use the tools
> Small addition to the identity-provider-cli and user-cli docs

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- idiss/Cargo.toml
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Prepare for release of
- concordium-base
- concordium-wasm
- concordium-smart-contract-engine.
> Release all

- rust-src/concordium_base/src/cis4_types.rs
we should use camelCase consistently.
> Fix JSON serialization of credentialInfo.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- rust-src/concordium_base/src/web3id/mod.rs
> Change epoch for Web3ID timestamps.

- rust-src/concordium_base/CHANGELOG.md
> Update changelog for release.

- rust-src/concordium_base/src/hashes.rs
> Introduce successor proof hash type.

- identity-provider-service/CHANGELOG.md
- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- identity-provider-service/src/bin/main.rs
Fixes #316
- Added improved error handling, so that the wallet can handle some of the errors
> Added improved error handling in the identity provider service

- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
Make the changelog more consistent.
> Fix changelog consistency.

- .github/workflows/build-test-contracts-common.yaml
- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/contracts-common/concordium-contracts-common-derive/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common-derive/Cargo.toml
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
Prepare
-  contracts-common(-derive)
- concordium-sc-engine
- concordium-base
for release by updating changelongs and bumping versions.
> Bump versions for release of smart contract related libraries.

- rust-src/concordium_base/CHANGELOG.md
Release 3.1.1 to release cargo-concordium.
> Update changelog for release of concordium-base.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-test/Cargo.lock
Update contracts-common to 8.1.1 for release.
> Update contracts-common to version 8.1.1.

- haskell-src/Concordium/Types/Queries.hs
Remove V1 API.
- bump submodule
- remove blocksummary type since it is not used either in the node or in the client.
No other functionality is removed from the base libraries. While some JSON serialization might in principle be removable, most of it is still used in the client and might also come in handy for testing, so is kept.
> Bump GRPC API to remove V1 API.

- .github/workflows/build-test-contracts-common.yaml
- .github/workflows/build-test-smart-contracts.yaml
- .github/workflows/build-test-sources.yaml
- smart-contracts/contracts-common/concordium-contracts-common/src/schema.rs
- smart-contracts/contracts-common/concordium-contracts-common/src/schema_json.rs
- smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Fix actions so that the contracts-common actions actually run.
Also avoid using obsolete actions-rs actions and update checkout action to avoid warnings about obsolete versions.
> Attempt to fix CI.

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/dodis_yampolskiy_prf/secret.rs
Adds FromStr and Display implementations for PRF keys.
> Add FromStr and Display impls for PRF keys

- identity-provider-service/Cargo.lock
- identity-provider-service/Cargo.toml
- idiss/Cargo.lock
- idiss/Cargo.toml
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Prepare for release of.
- concordium-base
- concordium-contracts-common
- concordium-smart-contract-engine
- concordium-wasm
Bump version numbers and changelogs.
> Prepare for release

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/cis2_types.rs
- rust-src/concordium_base/src/cis4_types.rs
Expose fields of CIS4 events to make them accessible.
Closes https://github.com/Concordium/concordium-rust-sdk/issues/187
> Expose fields of events in CIS4.

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- idiss/Cargo.toml
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/contracts-common/concordium-contracts-common-derive/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-test/Cargo.lock
Bump versions to prepare release.
> Bump versions for releases.

- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Needed for https://github.com/Concordium/concordium-rust-smart-contracts/issues/422.
> Derive serde::Serialize and serde::Deserialize for PublicKeyEd25519

- haskell-src/Concordium/Cost.hs
- haskell-src/Concordium/Wasm.hs
- mobile_wallet/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/lib.rs
- rust-src/concordium_base/src/web3id/mod.rs
Enable credential proof verification in the JS sdk
> Web3id serde

- haskell-src/Concordium/Types/Queries.hs
With the cooldown changes, the `PoolStatus` datastructure was split into `BakerPoolStatus` and `PassiveDelegationStatus`, and `ActiveBakerPoolStatus` was factored out (under a `Maybe`). This last change in particular meant that the `deriveJSON` instances for `BakerPoolStatus` would not be backwards compatible. This rectifies that.
- Implement manual `ToJSON` and `FromJSON` instances for `BakerPoolStatus` that inline the `ActiveBakerPoolStatus` fields.
> Revise ToJSON for BakerPoolStatus for compatibility.

- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
- smart-contracts/wasm-chain-integration/Cargo.lock
Prepare for release:
- `concordium_base` 6.0.0
- `concordium-contracts-common` 9.2.0
- Update changelogs.
- Bump version numbers.
> Prepare for release.

- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/Cargo.lock
- smart-contracts/wasm-chain-integration/Cargo.toml
- smart-contracts/wasm-transform/CHANGELOG.md
- smart-contracts/wasm-transform/Cargo.toml
Prepare release of smart contract engine related crates
> Prepare release of smart contract engine crates

- .github/workflows/build-test-contracts-common.yaml
- .github/workflows/build-test-smart-contracts.yaml
- .github/workflows/build-test-sources.yaml
- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/CHANGELOG.md
- mobile_wallet/Cargo.lock
- mobile_wallet/Cargo.toml
- mobile_wallet/android/build-android.sh
- mobile_wallet/src/lib.rs
- rust-bins/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/encrypted_transfers/ffi.rs
- rust-src/concordium_base/src/encrypted_transfers/mod.rs
- rust-src/concordium_base/src/transactions.rs
- smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md
- smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Merge changes from the 7.0 release branch into main.
- Changes as part of releases.
> Merge release branch into main

- .github/workflows/release-identity-provider-service.yaml
Update base image for building the identity provider service.
> Update base image for identity provider service

- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types/Parameters.hs
- haskell-src/Concordium/Types/Transactions.hs
Add support for newly introduced special transaction outcomes for validator suspension. Depends on https://github.com/Concordium/concordium-base/pull/571.
see above.
> Add special transaction outcome

- haskell-src/Concordium/Types/Accounts.hs
Rename a field in the `bakerInfoEx` data type. Fixes  #572. We will also have to change `concordium-node`.
See above.
> Rename `bieAccountIsSuspended` -> `bieIsSuspended`

- haskell-src/Concordium/Types/Accounts.hs
Add a doc string to `bieIsSuspended`.
> add doc string to bieIsSuspended

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/cis2_types.rs
Add constructor for cis2 type `TokenAddress`.
> Add token address constructor

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/updates.rs
> Add getter function

- smart-contracts/wasm-chain-integration/CHANGELOG.md
> Fixed changelog

- haskell-src/Concordium/Types/Accounts.hs
A cosmetic renaming to align with the rest of the field names.
> plt: cosmetic renaming

- haskell-bins/genesis/Genesis.hs
- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Genesis/Parameters.hs
- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Migration.hs
- haskell-src/Concordium/Types/Parameters.hs
- haskell-src/Concordium/Types/ProtocolVersion.hs
- haskell-src/Concordium/Types/Queries.hs
- haskell-src/Concordium/Types/Queries/Tokens.hs
- haskell-src/Concordium/Types/UpdateQueues.hs
- haskell-src/Concordium/Types/Updates.hs
- haskell-tests/Generators.hs
- haskell-tests/Genesis/ParametersSpec.hs
- haskell-tests/Types/ParametersSpec.hs
- haskell-tests/Types/TokenIdSpec.hs
- haskell-tests/Types/UpdatesSpec.hs
Base support for CreatePLT update payload.
Depends on https://github.com/Concordium/concordium-grpc-api/pull/86
and is related to https://github.com/Concordium/concordium-node/pull/1361
> Introduce types and implemenations for CreatePLT update payload

- haskell-src/Concordium/GRPC2.hs
To add the `ToProto` instance for `TokenId`. Needed for https://github.com/Concordium/concordium-node/pull/1367. 
- `ToProto` instance added
> Add ToProto for TokenId.

- haskell-src/Concordium/Cost.hs
- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Execution.hs
- haskell-tests/Generators.hs
- haskell-tests/Types/PayloadSerializationSpec.hs
Introduce types related to token holder transactions.
Related PR for grpc: https://github.com/Concordium/concordium-grpc-api/pull/88
Related PR for node: https://github.com/Concordium/concordium-node/pull/1368
> Types related to token holder transactions (ref NOD-697)

- haskell-src/Concordium/GRPC2.hs
Support the `tokens` field in `AccountInfo` `ToProto` instance.
- Add `tokens` to `ToProto AccountInfo`.
- `ToProto` instances for `TokenAmount`, `TokenAccountState` and `Token`.
> Update ToProto instances for AccountInfo.

- haskell-src/Concordium/GRPC2.hs
- haskell-src/Concordium/Types/Queries/Tokens.hs
Add support for GetTokenInfo.
- Add `TokenState` and `TokenInfo`.
- Add `ToProto` instances.
> Support GetTokenInfo

- cbor-schema/plt.cddl
This PR introduces a CDDL schema that defines the CBOR representation used by the protocol-level token transactions.
- Define `token-holder-transaction`.
- Define `token-governance-transaction`.
- Define `token-intialization-parameters`.
> Add CDDL schema for PLT transactions.

- haskell-src/Concordium/Types/Accounts.hs
- haskell-src/Concordium/Types/Queries/Tokens.hs
Related to: https://github.com/Concordium/concordium-client/pull/354
- Add `toJSON` and `fromJSON` instances to display tokens.
> Get account info query

- haskell-src/Concordium/Crypto/BlockSignature.hs
- haskell-src/Concordium/Crypto/ByteStringHelpers.hs
- haskell-src/Concordium/Crypto/EncryptedTransfers.hs
- haskell-src/Concordium/Crypto/SignatureScheme.hs
- haskell-src/Concordium/ID/Types.hs
- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Memo.hs
- haskell-src/Concordium/Types/Queries/Tokens.hs
- haskell-src/Concordium/Types/Tokens.hs
- haskell-src/Concordium/Wasm.hs
Related to:
https://github.com/Concordium/concordium-client/pull/356
> Get token info query

- haskell-tests/ConcordiumTests/Crypto/BlsSignature.hs
- haskell-tests/ConcordiumTests/Crypto/VRF.hs
- haskell-tests/Generators.hs
- haskell-tests/Types/AccountEncryptedAmountSpec.hs
- haskell-tests/Types/TransactionSerializationSpec.hs
Reduce the time to run the Haskell test suite.
- Reduce iterations on some of the more expensive property-based tests.
- Improve the performance of some expensive generators.
> Faster Haskell tests

- cbor-schema/plt.cddl
Adds event detail definitions to the plt token module cddl
- Factors out the details of each operation to be able to re-use them in the module specific event details
> Update plt cddl with module specific event details

- haskell-src/Concordium/Types/Queries/Tokens.hs
- haskell-src/Concordium/Types/Tokens.hs
- Improve display of `tokenId` without `"`
- Fix typo `tokenId` should be `tokenModuleRef`.
> Small fixes

- haskell-src/Concordium/Types.hs
- haskell-src/Concordium/Types/Execution.hs
- haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs
- haskell-src/Concordium/Utils/Encryption.hs
- haskell-tests/Types/CBOR.hs
Implement JSON serialization of CBOR encoded data inside token holder transaction
Implemented JSON serialization for relevant types. Example of token holder transaction
```json
{
"energy": 563,
"expiryTime": 1747397416,
"nonce": 6,
"payload": {
"operations": [
{
"transfer": {
"amount": 1,
"memo": {
"type": "cbor",
"value": "6474657374"
},
"recipient": {
"address": "3CBp9U5nJyLFk8r7Uh3mBHTB23r2pwRj5H3qcTtLtdribh8o1U",
"coininfo": "CCD",
"type": "account"
}
}
}
],
"tokenSymbol": "TK1",
"transactionType": "tokenHolder"
},
"signature": {
"0": {
"0": "8c59270581bfd9e2ed41ff04f70c48e4811272a61c98264e5b757bf996823d3e95ab4a038e3e16fbd1ea777dab3d8cb0e1ef66ecfa7d0a8ed63eeeb9495b610a"
}
},
"signer": "37GP3ChyTTX2gjHdBrKfaA5tbmEqM53kkxsSHYN4FmsQEsaq8V",
"version": 1
}
```
> json encode plt token holder operation

- cbor-schema/plt.cddl
Add a type describing metadata urls which are accompanied by an optional checksum.
> Add metadata url type to cddl

- rust-src/concordium_base/src/protocol_level_tokens/mod.rs
- rust-src/concordium_base/src/protocol_level_tokens/token_event.rs
- rust-src/concordium_base/src/protocol_level_tokens/token_holder.rs
Matching rust sdk PR https://github.com/Concordium/concordium-rust-sdk/pull/255
> Update types in rust src used for PLT in API

- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/src/protocol_level_tokens/token_operations.rs
- rust-src/concordium_base/src/transactions.rs
- rust-src/concordium_base/src/updates.rs
Rust changes  of https://github.com/Concordium/concordium-base/pull/678.
Same as https://github.com/Concordium/concordium-base/pull/678 but only Rust.
> Token update Rust changes

- haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs
> remove tags from TokenOperation

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
> Bump alpha version of concordium_base rust lib

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/Cargo.toml
- rust-src/concordium_base_derive/Cargo.toml
> Bump alpha version of base derive crate

- smart-contracts/wasm-chain-integration/CHANGELOG.md
- smart-contracts/wasm-chain-integration/src/v1/ffi.rs
Ref COR-700
Related PR in concordium-node https://github.com/Concordium/concordium-node/pull/1410
Introduce new FFI functions for interacting with the state trie.
> Extend FFI with lookup and insert functions for mutable state trie

- identity-provider-service/Cargo.lock
- idiss/Cargo.lock
- mobile_wallet/Cargo.lock
- rust-bins/Cargo.lock
- rust-src/Cargo.lock
- rust-src/concordium_base/CHANGELOG.md
- rust-src/concordium_base/Cargo.toml
- rust-src/concordium_base_derive/Cargo.toml
> Bump versions

- rust-src/concordium_base/src/protocol_level_tokens/token_reject_reason.rs
> Fix  typo in enum variant

- rust-src/concordium_base/CHANGELOG.md
> Address review comments

- .github/workflows/release-concordium-base-derive.yaml
- .gitignore
- rust-src/concordium_base_derive/Cargo.toml
Create release git action for concordium base derive
Create release git action
> fix: create release git action for concordium base derive
