Concordium/concordium-base

genesis-tools.Jenkinsfile, scripts/genesis-tools.Dockerfile
The current solution doesn't work because `docker build` wasn't called with `DOCKER_BUILDKIT` set.
But there isn't really any reason for needing it as we only use it for re-cloning out the repo that is already checked out in the pipeline.
If we need to build from a private fork, the jenkins job will just be redirected to build from that fork.
=> Fix genesis tools build process

.github/workflows/build-test.yaml, .github/workflows/rustfmt.yaml
Run workflows when marking a pull request as ready for review.
The default types are only `opened, synchronize, reopened`.
=> Run workflows when switching status from draft to ready for review.

rust-bins/src/bin/client.rs, rust-src/crypto_common/src/serde_impls.rs, rust-src/crypto_common/src/types.rs
Support using key indices as map keys in JSON.
Support parsing key indices from JSON strings.
=> Support parsing of key indices from strings in JSON.

haskell-src/Concordium/Common/Time.hs
Make `durationToNominalDiffTime` not lose any precision.
=> Make `durationToNominalDiffTime` not lose any precision.

rust-bins/src/bin/anonymity_revocation.rs, rust-bins/src/bin/keygen.rs, rust-bins/src/bin/utils.rs, rust-bins/src/lib.rs
Address https://github.com/Concordium/concordium-base/issues/19. 
The keygen tool now asks for a password twice to encrypt the generated keys under. If passwords are different, it will ask again.
The same has been done in the "utils" tool which can also encrypt data.
In the anonymity revocation tool the prints of decrypted data have been removed.
=> Ask for password confirmation and minor cleanup

mobile_wallet/Cargo.toml
Bump version. The previous one is no longer compatible since genesis generators are embedded.
=> Bump version of mobile libraries.

concordium-base.cabal, haskell-bins/genesis/Genesis.hs, haskell-src/Concordium/ID/Types.hs, haskell-src/Concordium/Types/Updates.hs, package.yaml
Make the genesis tool output the entire genesis.
Example output: [genesis-block.txt](https://github.com/Concordium/concordium-base/files/6397777/genesis-block.txt)
- Output the parts of genesis that was not yet printed.
- Try to pretty print as much as possible.
- Modify Show instances of UpdateKeysThreshold and AccountThreshold to simply print the number.
=> Print the entire genesis in the genesis tool.

rust-bins/docs/keygen.md, rust-bins/src/bin/keygen.rs
The same interface that used to exist is still supported, however all arguments
to the tool are now optional. If they are not supplied the relevant values are
queried interactively.
Make the AR keygen tool easier to use.
Query for input interactively if it is not supplied on the command-line.
```
Enter the path to the cryptographic parameters file: foo/global.json
Enter AR identity: 1
Enter the name of the AR: Foobar
Enter URL of the AR: foobar@baz
Enter description of the AR: blah
Output file name: ar-data-1.json
Output file for public data: ar-info-1.pub.json
Enter password to encrypt credentials (leave empty for no encryption): 
No password supplied, so output will not be encrypted.
Wrote private keys to ar-data-1.json.
Wrote public keys to ar-info-1.pub.json.
```
hard-to-understand …
=> Make the AR keygen tool interactive.

rust-bins/docs/keygen.md, rust-bins/src/bin/keygen.rs
Retry word entry on failure to make it easier to use the tool.
- Retry word entry on failure.
- Add an option to just use the system randomness. It really is good enough for all practical purposes so there is no harm in supporting this.
=> Retry word entry on failure and make it possible to run just with system randomness.

rust-bins/src/bin/client.rs, rust-bins/src/bin/keygen.rs
Make it easier to construct the genesis block.
Add a subcommand to the ID client that can combine credentials into an account.
=> Add small utility to combine credentials from the destkop wallet into a genesis account structure.

rust-bins/src/bin/client.rs
Fix bug in testing tool that made it rely on specific ordering.
Use the index in the map when linearized rather than as the key in the map.
=> Fix how IPS are queried to not rely on them being in order starting at 0

haskell-src/Concordium/Crypto/BlockSignature.hs, haskell-src/Concordium/Crypto/VRF.hs
Extra caution against corrupted key files.
Ensure that keypair consistency is checked whenever we read them.
Serialization performance for keypair serialization is worse now, but practically that should not matter since we don't constantly deserialize keypairs.
An alternative design that would remove this downside would be to add a "verifyKeyPair" function to ensure consistency.
But I think adding a check during serialization is more in-line with the current design (we also check that the public key is a valid curve point for example).
=> Verify that keys which are part of the keypair are mutually consistent.

rust-bins/src/bin/anonymity_revocation.rs
To make the --credential option optional when using `combine-prf` command to compute the prf key given the shares. 
If not provided, or if the provided credential is initial, it will assume that the given shares are enough (i.e. there are at least threshold many). The reason for this is that the initial credential does not contain the anonymity revocation threshold, so it wasn't possible to check if enough shares were given in the case of revoking the identity behind an initial account.
The --credential option is now optional, and if it is not provided, or the given credential is initial, the user is warned that it will assume that enough shares are given.
=> Add threshold parameter to anonymity revocation tool.

identity-provider-service/Cargo.lock, identity-provider-service/Cargo.toml, identity-provider-service/src/bin/main.rs, idiss/Cargo.lock, idiss/Cargo.toml, idiss/src/lib.rs, rust-bins/src/bin/anonymity_revocation.rs, rust-src/id/src/types.rs
Simplify the anonymity revocation process, and make the information in the AR record self-contained.
- Add a field to the anonymity revocation record.
- Update the AR tool to use the new field, and remove the old `credential` argument.
- Update the idiss library to return the new field.
=> Add revocation threshold to the anonymity revocation record.

CHANGELOG.md, mobile_wallet/src/lib.rs, rust-bins/wallet-notes/README.md
Closes #30  
The input object of create_id_request_and_private_data can optionally contain a field specifying an anonymity revocation threshold. If it does we check that it is at least 1 and not more than the number of anonymity revokers. If not the functionality is the same as before.
=> Optional arThreshold field added in create_id_request

rust-src/aggregate_sig/Cargo.toml, rust-src/aggregate_sig/src/aggregate_sig.rs, rust-src/aggregate_sig/src/lib.rs, rust-src/crypto_common/src/lib.rs, rust-src/crypto_common/src/types.rs, rust-src/crypto_common_derive/src/lib.rs, rust-src/encrypted_transfers/benches/enc_trans_benchmarks.rs, rust-src/encrypted_transfers/src/ffi.rs, rust-src/encrypted_transfers/src/lib.rs, rust-src/encrypted_transfers/src/proofs/generate_proofs.rs, rust-src/encrypted_transfers/src/types.rs, rust-src/id/src/types.rs
This mimics what is already done on the Haskell side.
Type safety changes just add a bit of safety, mimicking the types that already exist on the Haskell side.
The additional instances make it easier to use the types in external libraries.
- add a Timestamp type, mimicking the one in Concordium/Types.hs
- add EncryptedAmountIndex/AggIndex, replacing the previous use of u64 for both
- make the derive macros a bit more hygienic, avoiding some hard to understand errors.
=> Add a few trait implementations and a bit of type safety.

CHANGELOG.md, rust-src/id/src/types.rs
To fix the Display implementation for AttributeTag. It was off by one.
The Display implementation has been fixed.
=> Fix display for attributes.

rust-src/encrypted_transfers/src/proofs/enc_trans.rs, rust-src/id/src/sigma_protocols/aggregate_dlog.rs, rust-src/id/src/sigma_protocols/com_enc_eq.rs, rust-src/id/src/sigma_protocols/com_eq.rs, rust-src/id/src/sigma_protocols/com_eq_different_groups.rs, rust-src/id/src/sigma_protocols/com_eq_sig.rs, rust-src/id/src/sigma_protocols/com_lin.rs, rust-src/id/src/sigma_protocols/com_mult.rs, rust-src/id/src/sigma_protocols/dlog.rs, rust-src/random_oracle/src/lib.rs
Some tests of soundness of various protocols did not test for collision of RO challenge prefixes. These would happen with probability > 1/10^6, and thus make the tests fail in some rare cases.
Add tests checking if two randomly selected ROs are identical in case of unexpected verifications, when one is used for generating a proof and the other for verification.
=> Add checks for RO challenge prefix collision in soundness tests

rust-src/eddsa_ed25519/src/dlog_ed25519.rs
To construct a dlog proof for the bakers ecvrf keys the signature must be more generic.
- Make prove_dlog_ed25519 take generics for public key (`impl Serial`) and secret key (`impl AsRef<[u8]>`).
=> Support using ecvrf key with prove_dlog_ed25519 

rust-src/id/src/id_prover.rs, rust-src/id/src/id_verifier.rs
To take a reference to the credential data when proving ownership of account instead of consuming it.
Added above reference.
=> Add reference to credential data in prover function.

rust-src/ps_sig/src/public.rs
Verification of PS signatures was improved to reject dummy signatures of form (point_at_infinity, point_at_infinity) which are valid for any combination of message and public_key.
Signature verification now rejects signatures where the first group element is the point at infinity in G1, as per the original Pointcheval-Sanders paper. A test was also added to prevent future regressions.
=> Improve PS signature verification; add test to prevent regression.

concordium-base.cabal, haskell-src/Concordium/Crypto/EncryptedTransfers.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Utils/Serialization.hs, haskell-tests/Spec.hs, haskell-tests/Types/PayloadSerializationSpec.hs, haskell-tests/Types/TransactionSummarySpec.hs
Serialization defines the transaction outcome hash, which is part of blocks, and
therefore block hashes. Hence it is important that it is well-defined and not
accidentally changed. Making it explicit helps with that. Additionally it will more easily support changes to the relevant types while retaining backwards compatibility.
Write serialization instances manually instead of using generic deriving.
=> Make serialization instances for transaction outcomes explicit.

haskell-src/Concordium/Types/Parameters.hs
At some point we removed some parameters from genesis, and to maintain compatibility we serialized the remaining parameters in a hacky way. This is no longer used.
Remove unused and obsolete functions.
=> Remove unused legacy functions.

rust-bins/Cargo.lock, rust-bins/Cargo.toml, rust-bins/docs/keygen.md, rust-bins/src/bin/keygen.rs, rust-src/Cargo.lock, rust-src/keygen_bls/CHANGELOG.md, rust-src/keygen_bls/Cargo.toml, rust-src/keygen_bls/src/lib.rs
To fix the BLS keygen. Closes https://github.com/Concordium/concordium-base/issues/90. 
* The function `keygen_bls` has been corrected according to the standard (cf. https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-2.3) so that it now uses the correct endianness. 
* Test vectors have been added.
* A changelog has been added.
* Version increased to 2.0.0. 
=> Fix keygen, increase version, add test vectors and changelog.

haskell-src/Concordium/ID/Types.hs, rust-src/id/src/types.rs
We might have additional attributes in the immediate future, this changes the JSON instance for attribute tags so that they provide the numeric value instead of mapping all of them to unnamed.
Change the to/from json instances for AttributeTag to not lose information. This does not affect any current uses since all attribute tags are currently in the list of known attributes.
=> Improve the JSON instances for attribute tags so they provide information in case of unrecognized tag.

rust-bins/docs/identity-provider-cli.md, rust-bins/docs/user-cli.md, rust-bins/src/bin/client.rs, rust-bins/src/bin/identity_provider_cli.rs, rust-bins/src/bin/keygen.rs, rust-bins/src/bin/user_cli.rs, rust-bins/src/lib.rs, rust-src/id/src/types.rs
To make two binaries for interaction between an enterprise and an identity provider in order to create an identity and an account.
* A binary `user_cli` has been provided for the user's side of the process.
* A binary `identity_provider_cli` has been provided for the identity provider's side of the process.
* The existing binary `client` has been polished a bit.
* Two readmes have been added for the newly introduced binaries.
=> Make separate binaries for user and identity provider.

rust-bins/Cargo.lock, rust-bins/src/bin/user_cli.rs
To decrypt id-use-data if necessary when creating credentials
* The `create-credential` command now decrypts the id-use-data if it is encrypted.
=> Decrypt id-use-data if necessary.

rust-bins/id-client-notes/instructions.md
Document how to get the account keys, which are generated by the id-client tool, accepted by concordium-client.
(and that is to add the commitments field to the credential's content)
=> Update id-client-notes/instructions to help importing account into concordium-client

rust-bins/docs/user-cli.md
Make the command line copyable.
Add missing `\`.
=> Fix command line examples.

idiss-csharp/CHANGELOG.md, idiss-csharp/IdissLib/IdissLib.csproj, idiss-csharp/IdissLib/Types.cs, idiss-csharp/IdissLibTest/IdissTests.cs
Fix JSON serialization of AR records.
Since JSON serialization is derived the field names must match what is expected from the formatting of the anonymity revocation threshold.
=> Fix JSON serialization of AR records.

rust-bins/docs/keygen.md, rust-bins/src/bin/keygen.rs
Add ability to generate governance keys to the keygen tool.
Add a subcommand to the keygen tool.
=> Add ability to generate governance keys to the keygen tool.

rust-bins/src/bin/client.rs
Consistency of outputss between genesis tool and the id-client.
Output credential with commitments only, without proofs. Note that the credential is output separately, so there is no loss of information.
=> When generating account keys, output them in a format compatible with genesis.

haskell-src/Concordium/ID/Types.hs, haskell-src/Concordium/Types/Updates.hs
As part of https://github.com/Concordium/concordium-node/pull/217 the `Scheduler` now relies on checking that the hashes of `AccountInformation` and `UpdateKeysCollection` matches the current ones on the chain.
This is security critical code thus the two checks deserved being their own functions (with appropriate commentary) instead of inline checks. 
Introduced `matchesAccountInformation` and `matchesUpdateKeysCollection` functions for checking if a given `AccountInformation` matches the given `hash` and vice versa for `UpdateKeysCollection`
=> Functions for checking public credentials in regard to a `hash`

concordium-base.cabal, haskell-bins/genesis/Genesis.hs, haskell-src/Concordium/Constants.hs, haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/P4.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/InvokeContract.hs, haskell-src/Concordium/Types/ProtocolVersion.hs, haskell-src/Concordium/Wasm.hs, haskell-tests/Types/PayloadSerializationSpec.hs, haskell-tests/Types/TransactionGen.hs, haskell-tests/Types/TransactionSummarySpec.hs, rust-bins/docs/user-cli.md
Auxiliary types to support V1 version of smart contracts with synchronous contract calls.
- Introduce an "Entrypoint" type analogous to contract name and receive name. This is used when invoking a V1 contract since the name of the contract is already known from the address.
- Introduce new events that can result from contract execution.
- P4 boilerplate. This will have to change by the time of release of P4 node, but is needed to get any testing done of the features.
=> Sync calls

haskell-src/Concordium/Types/Execution.hs, haskell-tests/Types/TransactionSummarySpec.hs
Allow new code to successfully parse old JSON responses. In particular this applies to Init and Update contract. They now have an added contract version field which would break compatibility (in the specific sense mentioned) for the automatically generated parsers.
Replace automatically generated instance with manually written ones, defaulting some values during parsing.
I have also added a test that serialization is invertible.
Additionally I have run a test that checks that the new instance is compatible with the automatically generated one. However this is not part of this PR since that property is only interesting once, and is not part of the semantics of the type.
=> Manual instances of Event JSON serialization.

haskell-src/Concordium/Wasm.hs
Minor auxiliary definitions related to V1 contract state.
In support of https://github.com/Concordium/concordium-node/pull/243
The main change is the addition of InstanceInfo type that is meant to be used as a response in GetInstanceInfo query.
The rest is boilerplate code.
=> V1 contract state

identity-provider-service/Cargo.lock, identity-provider-service/Cargo.toml, identity-provider-service/src/bin/main.rs
`remove_file` returns an error if the file does not exist. This, in combination with not checking whether a submission is still pending, can lead to a panic.
Fix a panic due to concurrent requests.
Check whether the submission has already been marked finalized/deleted before attempting to delete it again.
Do this in the scope of an acquired lock.
=> Fix a race condition in the identity provider service.

haskell-src/Concordium/Types.hs
It is a wrapper type for other types used to identify accounts.
To help identify/query accounts with multiple types.
Adds `AccountIdentifier` type.
=> Adds AccountIdentifier type.

mobile_wallet/CHANGELOG.md, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, rust-bins/wallet-notes/README.md, rust-bins/wallet-notes/files/2-create_configure_delegation_transaction-input.json, rust-src/crypto_common/src/types.rs, rust-src/id/src/types.rs
To rename L-pool to passive delegation.
* Renamed field `DelegateToLPool` to `DelegatePassive` in the DelegationTarget type in crypto_common.
* Renamed JSON field from `L-Pool` to `Passive` in the DelegationTarget type in crypto_common and updated the README accordingly. 
* Updated example input files accordingly to renaming. 
* Increased version from 0.11.0 to 0.12.0
* Apparently clippy wasn't happy about a line of the form `return None;` in id/src/types.rs, so it is replaced by `None`. 
=> Rename L-pool to passive delegation in mobile wallet library

.github/workflows/build-test.yaml
Ensure clippy failure fails the CI run.
Deny all clippy warnings.
=> Make clippy return a non-zero error code upon any warnings.

rust-src/crypto_common/src/types.rs
Helper functions needed in the rust sdk.
=> Add helper functions to the Amount type.

rust-bins/src/bin/trace_account.rs, rust-src/crypto_common/src/types.rs, rust-src/encrypted_transfers/src/ffi.rs
Since the crypto common crate is used in the rust sdk it is not great we still have the GTU name.
Since a major release is coming up now is a good opportunity to change it.
- rename microgtu to microccd as the AMount field type.
=> Rename field name from GTU to CCD.

haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Block.hs, haskell-src/Concordium/Types/Parameters.hs
Tests added in https://github.com/Concordium/concordium-node/pull/335 require several types to have instances of `Arbitrary`.
`AmountFraction`, `Slot`, `MintDistribution`, `PartsPerHundredThousand` got instances of Arbitrary.
=> Added several Arbitrary instances

rust-src/id/src/account_holder.rs
This was left over during refactoring to isolate the use of Rc to core datatypes.
=> Remove leftover assignments.

rust-src/id/src/types.rs
Expose the account address constructor. It is needed in the rust SDK.
=> Expose account address field so it can be constructed from a byte array.

mobile_wallet/CHANGELOG.md, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, mobile_wallet/android/mobile_wallet_lib/src/main/java/com/concordium/mobile_wallet_lib/wallet.kt, mobile_wallet/mobile_wallet.h, mobile_wallet/src/android.rs, mobile_wallet/src/lib.rs, rust-bins/wallet-notes/README.md, rust-src/Cargo.lock, rust-src/Cargo.toml, rust-src/ed25519_hd_key_derivation/Cargo.toml, rust-src/ed25519_hd_key_derivation/src/lib.rs, rust-src/key_derivation/Cargo.toml, rust-src/key_derivation/src/lib.rs
Add library support for the mobile wallets to derive identity and account keys from a seed phrase, as well as blinding  randomness and attribute commitment randomness.
- Added a library (_ed25519_hd_key_derivation_) that implements [SLIP0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md) for ed25519 specifically.
- Added a library (_key_derivation_) that implements the Concordium key derivation as specified in the cryptographic blue paper.
- Note that the tests for this library check keys against keys I have derived using a TypeScript implementation of the same key derivation scheme. I will be testing by deriving keys for the same paths in the Ledger repository afterwards as extra verification.
- Added Android and iOS wrappers for getting identity keys, blinding …
=> Create libraries for deterministic key derivation

haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/Base.hs, haskell-src/Concordium/Genesis/Data/P1.hs, haskell-src/Concordium/Genesis/Data/P2.hs, haskell-src/Concordium/Genesis/Data/P3.hs, haskell-src/Concordium/Genesis/Data/P4.hs, haskell-src/Concordium/Types/ProtocolVersion.hs
This PR has auxiliary type definitions and helper functions in support of https://github.com/Concordium/concordium-node/issues/340
The main change is the introduction of `GenesisConfiguration` which contains data that consensus needs for running.
This is much less data (in general) than what is contained in the genesis block, since the latter contains the serialization of the block state.
I chose to add this type here and not in the consensus package since it is tightly related to the GenesisData type. In particular it is crucial that serialization of both are kept in sync so that GenesisConfiguration can always be deserialized from the serialization of GenesisData.
=> Avoid loading genesis

haskell-src/Concordium/ID/Types.hs, haskell-src/Data/FixedByteString.hs
The changes made in https://github.com/Concordium/concordium-node/pull/366 depend on this PR.
Defined `RawCredentialRegistrationID`.
=> Added a byte representation type for CredentialRegistrationID

haskell-src/Concordium/ID/Types.hs, haskell-src/Concordium/Types.hs
Followup to https://github.com/Concordium/concordium-base/pull/165
Required in the context of https://github.com/Concordium/concordium-node/pull/366/files/9cd10116a4cb25167486060edc6f9d27d26e9cd1#r886047507
Changed the `CredRegId` field type in `AccountIdentifier` to `RawCredentialRegistrationID`.
=> Use RawCredentialRegistrationID in AccountIdentifier

haskell-src/Concordium/ID/Types.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Accounts.hs, haskell-src/Concordium/Types/Transactions.hs, haskell-src/Concordium/Wasm.hs
Auxiliary changes to speed up node startup.
The main change is to make the types for account credentials and account encryption keys less strict when these are used in trusted contexts (e.g., when the value has already been verified). These are the "Raw" account encryption keys and "Raw" credential registration IDs.
The reason this is beneficial is that a raw value is substantially (orders of magnitude) cheaper to deserialize, as well as taking up around 1/3 of the space (for these two cases).
See https://github.com/Concordium/concordium-node/pull/377 for more details as to why this makes sense.
=> Speed up credential loading

rust-src/id/src/lib.rs
Since PRF keys are needed/visible in credentials, it is useful to be able to just use them through the id crate, without having to import the prf crate manually.
Concretely this is useful in the rust SDK.
Re-export the prf key crate from the id crate.
=> Re-export for use in the SDK.

haskell-src/Concordium/Types/DummyData.hs
This fixes incorrect cost accounting in the function `Concordium.Types.DummyData.makeTransferTransaction`.
The cost accounting is handled using functions from `Concordium.Cost` instead of hard-coded values.
=> Fix dummy transaction cost accounting

identity-provider-service/README.md, identity-provider-service/html/attribute_form.html, identity-provider-service/src/bin/identity_verifier.rs, identity-provider-service/src/bin/main.rs
Introduce failing capabilities to the internal test identity provider
- Add endpoint that returns bad request.
- Add options when picking attributes to:
- Fail identity
- Pick how long the failing identity should be pending
- Pick expiry of the identity
hard-to-understand areas
=> Identity provider service fail

concordium-base.cabal, package.yaml
Fix the windows build by adding a system dependency. This seems to be needed with Rust 1.62 (and some older versions as well, although I have not pinpointed exactly which version is first that needs this).
=> Fix windows build with Rust 1.62.

smart-contracts/wasm-chain-integration/src/v1/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/trie/low_level.rs, smart-contracts/wasm-chain-integration/src/v1/trie/tests.rs
Addresses https://github.com/Concordium/concordium-node/issues/462
This PR evicts smart contract state from memory by simply not caching the state. 
- Evicting state references by converting them to 'Disk' as opposed to 'Cached' references.
- Removed `cache_persistent_state_v1` as sc state should no longer be cached on startup.
=> uncache v1 state.

smart-contracts/wasm-chain-integration/src/v1/trie/low_level.rs
Fix a bug where the cached ref did not get stored.
Store it
=> Store the ref.

smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.toml, smart-contracts/wasm-chain-integration/src/lib.rs, smart-contracts/wasm-chain-integration/src/v0/ffi.rs, smart-contracts/wasm-chain-integration/src/v0/types.rs, smart-contracts/wasm-chain-integration/src/v1/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/trie/mod.rs
This also removes unused definition warnings when compiling with no default features.
Remove warnings when compiling with no default features.
- wasm-chain-integration now depends on ffi_helpers
- doubly defined macros are unified.
=> Unify macros that were defined twice.

smart-contracts/wasm-chain-integration/src/v1/trie/api.rs
Expose ability to efficiently iterate over the entire persistent state.
=> Add a trie helper method to be able to traverse persistent states.

.github/workflows/build-test-smart-contracts.yaml, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.toml, smart-contracts/wasm-chain-integration/src/v1/trie/api.rs
Make it easier to use the contract state in the rust sdk.
Expose contract state construction methods, from iterators, and from streams.
The latter is useful in combination with the grpc API since the return value there is naturally a stream. This allows us to not construct an intermediate representation in memory.
=> Add ability to construct contract state from iterators and streams.

smart-contracts/wasm-chain-integration/src/v0/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/mod.rs, smart-contracts/wasm-transform/src/artifact.rs
Revise the FFI interface for processing and invoking smart contracts.
- Processing smart contracts returns the artifact bytes, rather than a pointer to an artifact. (These bytes can then be stored without further FFI calls for serialization.)
- Invoking contract initialisation and receive functions takes in the artifact bytes, rather than an artifact pointer. The artifact bytes are only copied when the execution is suspended.
- FFI calls for managing artifact pointers are removed as they are now unneeded.
=> ffi api changes related to init and recv fun(s)

identity-provider-service/Cargo.lock, mobile_wallet/Cargo.lock, rust-bins/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-test/Cargo.lock
Fix out of sync lock files. The contracts-common dependency was updated in https://github.com/Concordium/concordium-base/pull/214 but the lock files were not regenerated .
Reflect the real version of the contracts-common dependency.
=> Update lock files to record the correct contracts-common version.

haskell-src/Concordium/Wasm.hs, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/benches/v1-host-functions.rs, smart-contracts/wasm-chain-integration/src/v1/crypto_primitives_tests.rs, smart-contracts/wasm-chain-integration/src/v1/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/mod.rs, smart-contracts/wasm-chain-integration/src/v1/tests.rs, smart-contracts/wasm-chain-integration/src/v1/types.rs
Fix bug in `resume_receive`, and clarify the usage.
This bug is not an issue on the node since the value that is supplied is the same for both state_changed flags. But if this function is used independently then it is not correct, and in any case it does not conform to the intent.
- Add documentation
- Use correct `state_changed` flag when informing the instance.
=> Add documentation to `resume_receive`, and fix a bug.

rust-src/bulletproofs/benches/smp_bench.rs, rust-src/bulletproofs/src/lib.rs, rust-src/bulletproofs/src/set_membership_proof.rs, rust-src/bulletproofs/src/utils.rs
Sets for set membership proofs contained u64s. This is not enough, e.g., for names.
Use curve scalars directly instead of converting from u64.
=> Changed sets to contain scalars instead of u64s.

haskell-src/Concordium/Constants.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Wasm.hs, smart-contracts/wasm-chain-integration/benches/v1-host-functions.rs, smart-contracts/wasm-chain-integration/benches/wasm.rs, smart-contracts/wasm-chain-integration/src/constants.rs, smart-contracts/wasm-chain-integration/src/v0/ffi.rs, smart-contracts/wasm-chain-integration/src/v0/mod.rs, smart-contracts/wasm-chain-integration/src/v1/crypto_primitives_tests.rs, smart-contracts/wasm-chain-integration/src/v1/ffi.rs, smart-contracts/wasm-chain-integration/src/v1/mod.rs
Relax restrictions for parameter and return value size and number of logs. See https://github.com/Concordium/concordium-node/pull/573 for more details.
Solves part of https://github.com/Concordium/concordium-node/issues/563.
- Add functions for getting the limits, which depend on the PV.
- Remove `Serialize` instance for `Parameter` as we now need the PV for determining the max size.
- Added put/get functions for it instead.
- Pass in the limits from the scheduler and save it in the init/receive host, to be used when relevant.
- Change the cost function for parameters larger than 1kb.
=> Relax smart contract restrictions

haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/ProtocolVersion.hs, haskell-src/Concordium/Types/Transactions.hs
Introduce  multiple versions of `TransactionOutcomes` which can be used for supporting different kinds of hashing schemes.
In particular from P5 and onwards we do not want to hash the exact `RejectReason` anymore. (See https://github.com/Concordium/concordium-node/issues/566)
There are two versions of `TransactionOutcomes` and these are determined by the `ProtocolVersion`. 
PV1 to PV4 makes use of `TransactionOutcomesVersion 0` (`TOV0`) while P5 uses `TOV1`. 
Further there is introduced a `TransactionSummaryV1` type which is just a `newtype` wrapper around the existing `TransactionSummary` type. The purpose of this is to allow for a different `HashableTo` instance which omits the exact reject reason in the computed hash.
=> Base changes supporting a new hashing scheme for transaction outcomes.

rust-src/bulletproofs/benches/benches.rs, rust-src/bulletproofs/src/inner_product_proof.rs, rust-src/bulletproofs/src/range_proof.rs, rust-src/bulletproofs/src/set_membership_proof.rs
There have been three different verification methods for range proofs: A naive one, an efficient one (which is actually used), and a more efficient one. This pull request changes the efficient verification to use the same inner-product verification as the set-membership proofs. This makes that method essentially as simple and modular as the naive one and almost as efficient as the more efficient one (the performance benefits of the more efficient one appear negligible, < 1% on a desktop PC).
- Use inner-product verification from set-membership proof for range-proof verification.
- Remove naive verification.
- Remove more efficient verification.
=> Simplify range proof verifier

rust-src/concordium_base/src/constants.rs
Fix parameter size limit for P5 in concordium-base.
=> Bump parameter size limit.

haskell-src/Concordium/Wasm.hs
Part of https://github.com/Concordium/concordium-wallet-proxy/issues/73
Use hex to display parameters and contract events using the Show instance. There is no advantage in the ugly `Parameter { ... }` display and this fixes a number of places in the client which have an ugly output.
=> Use hex encoding to display contract events and parameters.

smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.toml, smart-contracts/wasm-chain-integration/benches/wasm.rs, smart-contracts/wasm-chain-integration/src/utils.rs
Extend `TestHost` with new host function that calls a RNG. The purpose of this is to run QuickCheck test for Wasm code that runs on-chain and doesn't support random number generation.
=> Add RNG support to TestHost

rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/smart_contracts.rs, rust-src/crypto_common/src/version.rs, rust-src/encrypted_transfers/src/types.rs, rust-src/id/src/types.rs
Add some Eq/PartialEq instances to help with a state comparison tool for testing.
Derive PartialEq/Eq instances where necessary.
=> Add a number of equality instances for types in rust-src.

rust-src/concordium_base/src/base.rs
Helpers to extract pretty-printable election difficulty. This is needed in the new genesis creator tool.
=> Add a few helpers to get the election difficulty in a reasonable format.

rust-src/concordium_base/src/constants.rs, rust-src/concordium_base/src/transactions.rs, rust-src/concordium_base/src/updates.rs, rust-src/id/src/id_prover.rs, rust-src/id/src/id_verifier.rs
Make it less confusing to use baker related transactions in the rust SDK.
Mark baker related transactions that only apply to P1-P3 as deprecated, and hide them from generated documentation.
=> Mark functions that only apply to sending p1-p3 transactions as deprecated

rust-src/concordium_base/src/base.rs, rust-src/crypto_common/src/version.rs, rust-src/id/src/id_proof_types.rs, rust-src/id/src/id_verifier.rs, rust-src/id/src/types.rs
Various helpers related to id 2.0 proofs. This came up during development of an example for testing.
- Fix some bugs in the high level helpers for constructing statements.
- Expose additional helpers.
- Add construction functions for credential registration IDs.
=> Proof helpers

rust-src/concordium_base/src/hashes.rs, rust-src/concordium_base/src/smart_contracts.rs
Since modulereference and moduleref both appear in the API we must sometimes convert between them. This adds helpers to achieve that.
=> Add conversions between ModuleReference and ModuleRef.

rust-src/concordium_base/src/transactions.rs
Add helpers for constructing update_credentials and update_credential_keys transactions.
The helpers don't really add very much. The main thing is computing the cost, but it is good to have them for completeness.
=> Add helpers for update_credentials and update_credential_keys.

identity-provider-service/deployment.md, scripts/docker-compose.identity-provider-service.yaml
The actual variable name is `GLOBAL_CONTEXT`, not `GLOBAL`.
Fix documentation. No code is changed.
=> Fix deployment configuration documentation for the identity provider

haskell-src/Concordium/Utils/Serialization/Put.hs
Fix loading the project in HLS with ghc 9.2.5.
The root cause is the following issue https://gitlab.haskell.org/ghc/ghc/-/issues/21871
Be explicit about kinds to work around a compiler issue.
=> Fix loading the project with HLS 9.2.5.

identity-provider-service/Cargo.lock, idiss/Cargo.lock, mobile_wallet/Cargo.lock, rust-src/Cargo.lock
Fix a bug in JSON serialization of contract addresses according to the schema.
The fix in contracs-common. This just bumps the submodule.
Depends on
=> Fix schema's to_json for contract addresses.

concordium-base.cabal
Build the project with stack 2.9.1 as stack 2.7.5 produces warnings when building with ghc 9.2.5.
Updated the resulting cabal file. 
=> Build with stack 2.9.1. Update cabal file.

rust-src/concordium_base/src/hashes.rs
Added Hash trait to hashbytes type to be able to use it in data structures requiring the Hash trait (such as HashMap)
=> Add implementation for std::hash::Hash for HashBytes

.github/workflows/build-test-sources.yaml, .gitmodules, README.md, Setup.hs, concordium-base.cabal, haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Queries.hs, package.yaml, rust-src/concordium_base/src/base.rs
Move GRPC2 type definitions to concordium-base so that we don't have to duplicate generation and conversion both in the node and in the client.
There are only necessary changes apart from moving the module. Any further desired changes should be done 
afterwards.
=> Move grpc2 types to base.

rust-src/concordium_base/src/smart_contracts.rs
Add missing display implementation for parameters. Based on hex as other binary data is displayed.
=> Add display implementation for contract parameters.

haskell-src/Concordium/GRPC2.hs
Fix a bug in `ToProto` instance that omitted encrypted transfers.
=> Fix encrypted amount ToProto instance to include incoming amounts.

identity-provider-service/CHANGELOG.md, identity-provider-service/Cargo.lock, identity-provider-service/Cargo.toml, identity-provider-service/src/bin/main.rs
Allow duplicate requests as long as we don't have id object issued yet.
Note that this does mean that two concurrent requests with the same IDP will mean that only one of the identity objects is going to be retained.
That could also be fixed, but it requires adding more hacks on top of the hacky database we have at the moment, so I choose not to do this. In any case, that was a problem already before.
=> Allow duplicate requests as long as identities are not issued yet.

rust-src/curve_arithmetic/src/curve_arithmetic.rs
Remove the unnecessary `Display` supertrait from the `Curve` trait in `curve_arithmetics`.
Remove the `Display` supertrait from the `Curve` trait. 
=> remove Display trait

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Genesis/Data/Base.hs, haskell-src/Concordium/Genesis/Parameters.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Migration.hs, haskell-src/Concordium/Types/Parameters.hs, haskell-src/Concordium/Types/Queries.hs, haskell-src/Concordium/Types/UpdateQueues.hs, haskell-src/Concordium/Types/Updates.hs, haskell-tests/Generators.hs
Addresses https://github.com/Concordium/concordium-base/issues/303
Added a new `FinalizationCommitteeParameters` structure for holding the parameters deciding which bakers gets to join the finalization committee for the new consensus protocol.
In particular it holds the following: 
- Minimum number of bakers that should reside in the finalization committee. `minFinalizers`
- Maximum number of bakers allowed to join the finalization committee. `maxFinalizers`
- A threshold that together with the total staked ccd constitutes the minimum stake requirement for joining the finalization committee.
- Added the corresponding update queue
- Added the associated update and update payload types
- Supporting the updated grpc2 api https://github.com/Concordium/concordium-grpc-api/pull/35
**The …
=> New parameters for deciding finalization committe eligibility

identity-provider-service/CHANGELOG.md, identity-provider-service/Cargo.lock, identity-provider-service/Cargo.toml, identity-provider-service/html/attribute_form.html
Extend default ID doc expiry in ID verifier to 2030.
=> Extend default ID expirty to 2030.

rust-src/concordium_base/src/hashes.rs, rust-src/concordium_base/src/transactions.rs
Allow for accessing the byte array of the hash directly.
There is no reason to hide this since the SHA256 hash will not change.
=> A bit of documentation and make the inner hash field public.

haskell-bins/genesis/Genesis.hs
Fixes https://github.com/Concordium/concordium-base/issues/345
Add function `showConditionally` and use it for printing types wrapped in `Conditionally`. 
=> Remove code-leftovers when printing values wrapped in `Conditionally` in `genesis print-genesis`.

.github/workflows/build-test-smart-contracts.yaml, .github/workflows/build-test-sources.yaml, rust-src/concordium_base/src/transactions.rs, rust-src/concordium_base/src/updates.rs
Update Rust fmt to `2023-04-01` to match other Rust repos
- Update version in CI jobs
- Fix minor formatting issues
=> Update Rust fmt to `2023-04-01`

mobile_wallet/CHANGELOG.md, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, mobile_wallet/android/mobile_wallet_lib/src/main/java/com/concordium/mobile_wallet_lib/wallet.kt, mobile_wallet/mobile_wallet.h, mobile_wallet/src/android.rs, mobile_wallet/src/lib.rs, rust-bins/Cargo.lock, rust-bins/wallet-notes/README.md, rust-src/Cargo.lock, rust-src/key_derivation/Cargo.toml, rust-src/key_derivation/src/lib.rs
Add support for deriving keys for verifiable credentials. In particular also expose this functionality to the mobile libraries for when they are going to implement Web3 ID functionality.
- Updated `key_derivation` with methods for getting the public key, signing key and encryption key required for a verifiable credential.
- Updated mobile libraries to expose the new functionality in `key_derivation`.
=> Web3id key derivation

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/common/types.rs, rust-src/concordium_base/src/updates.rs
Update types to support protocol version 6.
Depends on https://github.com/Concordium/concordium-contracts-common/pull/85.
Related to https://github.com/Concordium/concordium-rust-sdk/pull/92
- Introduce `Ratio` struct for implementing serde and the serialization of the node.
- Extend enums `UpdatePayload` and `UpdateType` with variants introduced in protocol version 6.
=> Introduce Ratio type and add p6 variants to UpdatePayload and UpdateType

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/common/serialize.rs, rust-src/concordium_base/src/common/types.rs, rust-src/concordium_base/src/updates.rs
Introduces changes needed for genesis-creator to support P6
Related to https://github.com/Concordium/concordium-misc-tools/pull/51
- Implement `Serial` for `num::rational::Ratio<u64>` and `Duration`.
- Introduce types for protocol version 6: `ChainParameterVersion2`, `GASRewardsCPV1`, `TimeoutParameters` and `FinalizationCommitteeParameters`.
=> Add types for P6 GenesisData

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Queries.hs
Related to https://github.com/Concordium/concordium-node/issues/837.
Should be merged with https://github.com/Concordium/concordium-grpc-api/pull/36 and https://github.com/Concordium/concordium-node/pull/838.
- Update grpc api submodule and types for the node accordingly.
=> Support block height as block identifier in gRPC v2 block queries

haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/BaseV1.hs, haskell-src/Concordium/Types/Accounts.hs
Changes to base to support the multiversion runner integration for new consensus.
- Project `CoreGenesisParametersV1` from genesis data for consensus version 1.
- Specialised `toAccountStakingInfoP4 ` that does not require epoch conversion from P4 onwards.
=> New consensus multiversion runner integration

identity-provider-service/html/attribute_form.html
All our encoding assumes UTF8 strings, so to use special characters as names we need the verifier's form to have UTF8 encoding, otherwise special characters can get garbled.
=> Force character encoding of the form to be utf8.

haskell-src/Concordium/Types/Parameters.hs
Partly fixes https://github.com/Concordium/concordium-base/issues/327 by checking the denominators when deserializing the `TimeoutParameters`.
Introduced two checks that make sure that we fail properly if the provided denominator of either the `timeoutIncrease` or `timeoutDecrease` are zero.
=> Check denominator when deserializing TimeoutParameters

haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/P6.hs, haskell-src/Concordium/Types/Migration.hs
Address https://github.com/Concordium/concordium-node/issues/856
- Introduce migration parameters for P5->P6 protocol update. 
In particular `StateMigrationParametersP5ToP6` is added to the `StateMigrationParameters` which yields the  `StateMigrationData` for protocol 6.
The `StateMigrationData` holds onto the chain parameters that must be supplied for the protocol update P5->P6.
- Consensus parameters for the new chain parameters version V2. These parameters are related to the new consensus protocol.
- Finalization committee parameters. The parameters that determines size and required stake of the finalization committee used in CPV2.
=> P6 protocol update

haskell-src/Concordium/Genesis/Data/P6.hs
Reuse the existing epoch duration instead of setting it via the protocol update payload.
=> Reuse epoch duration from previous protocol.

mobile_wallet/src/lib.rs, rust-src/concordium_base/src/cis4_types.rs, rust-src/concordium_base/src/web3id/mod.rs, rust-src/key_derivation/src/lib.rs
Revise web3id proofs since we are no longer storing commitments on the chain.
- Commitments are now sent as part of the proof.
- The signature on the commitments is checked as part of proof verification.
- Change the derivation path for holder keys to include the contract address.
- Remove generating encryption key from the seed.
=> Revise web3id proofs.

rust-src/concordium_base/src/common/serialize.rs, rust-src/concordium_base/src/id/account_holder.rs, rust-src/concordium_base/src/id/id_prover.rs, rust-src/concordium_base/src/id/id_verifier.rs, rust-src/concordium_base/src/id/types.rs, rust-src/concordium_base/src/web3id/did.rs, rust-src/concordium_base/src/web3id/mod.rs, rust-src/key_derivation/src/lib.rs
Revise credentials
- The issuer now additionally signs the contract address.
- The JSON format of Web3IdCredential now follows W3C "standard".
- There are no more attribute tags (u8). String names are used in proofs and inputs now for Web3Id stuff.
=> Revise credentials

mobile_wallet/src/lib.rs, rust-src/concordium_base/benches/bulletproofs.rs, rust-src/concordium_base/benches/set_proof_bench.rs, rust-src/concordium_base/src/bulletproofs/range_proof.rs, rust-src/concordium_base/src/bulletproofs/set_membership_proof.rs, rust-src/concordium_base/src/bulletproofs/set_non_membership_proof.rs, rust-src/concordium_base/src/encrypted_transfers/proofs/generate_proofs.rs, rust-src/concordium_base/src/id/account_holder.rs, rust-src/concordium_base/src/id/id_proof_types.rs, rust-src/concordium_base/src/id/id_prover.rs, rust-src/concordium_base/src/id/id_verifier.rs, rust-src/concordium_base/src/id/identity_provider.rs, rust-src/concordium_base/src/id/sigma_protocols/com_lin.rs, rust-src/concordium_base/src/id/types.rs, rust-src/concordium_base/src/web3id/mod.rs
Introduce a new proof version in which
https://github.com/Concordium/concordium-base/issues/379 is addressed. In the new proof version bulletproofs and set (non-)membership proofs will add public information explicitly into the transcript.
* New enum type `ProofVersion` introduced.
* Prover and verifier functions now takes a proof version
* For Web3ID we only use Version 2
* In Version 2, all public information related to the proven statement are added to the transcript. This includes the concrete bulletproof generaters used and the commitment keys. For ranges [0, 2^n) (i.e. the core bulletproofs), n is also added to the transcript. For general ranges [a,b), a and b are added to the transcript. 
=> Add proof version and improve range proofs

rust-src/concordium_base/src/curve_arithmetic/bls12_381_instance.rs, rust-src/concordium_base/src/curve_arithmetic/mod.rs
They are not used, and their functionality is hidden behind serialization.
=> Remove the (de)`compressed` functions from the Curve trait.

rust-bins/CHANGELOG.md, rust-bins/Cargo.lock, rust-bins/Cargo.toml, rust-bins/src/bin/user_cli.rs
The user_cli tool was unable to accept the `account` flag as it conflicted with the `expiry flag` that was always set due to a default value being provided.
I removed the mutual exclusivity of the flags. 
=> user_cli tool bugfix: Could not accept the account flag

identity-provider-service/Cargo.lock, idiss/Cargo.lock, mobile_wallet/Cargo.lock, rust-bins/Cargo.lock, rust-src/Cargo.lock, rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/Cargo.toml, rust-src/concordium_base/src/common/impls.rs, rust-src/concordium_base/src/web3id/mod.rs, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.toml, smart-contracts/wasm-test/Cargo.lock, smart-contracts/wasm-transform/Cargo.toml
Add a new timestamp type to web3id attributes.
The JSON serialization of this value is an object
```json
{
"type": "date-time",
"timestamp": "2016-09-01T10:11:12Z"
}
```
Add new variant to Web3IdAttribute.
Bump contracts-common (this is why all the lock files are updated).
=> Add timestamp to web3id credential types.

mobile_wallet/Cargo.lock, rust-bins/Cargo.lock, rust-src/Cargo.lock, rust-src/key_derivation/Cargo.toml, rust-src/key_derivation/src/lib.rs
Add `get_verifiable_credential_backup_encryption_key` to `ConcordiumHdWallet` struct in the `key_derivation` module.
- Added the method.
- Added some tests for it.
=> get verifiable credential backup encryption key

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/cis4_types.rs
Concordia needs to send credential status through a JSON API, so `Serialize` and `Deserialize` need to be derived.
Added the derive.
=> Derive Serialize/Deserialize for CredentialStatus

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/web3id/mod.rs
The Display implementation was still using the old epoch.
=> Fix the display for web3id attributes.

rust-src/Cargo.lock, rust-src/concordium_base/src/id/types.rs
Some consumers of concordium-base get deprecation warnings if using a newer version of the chrono dependency, which is allowed according to the range bounds we have.
This fixes the issue by using the new, non-deprecated function.
=> Remove the use of deprecated chrono function.

identity-provider-service/CHANGELOG.md, identity-provider-service/Cargo.lock, identity-provider-service/Cargo.toml, identity-provider-service/src/bin/main.rs
Change the identity provider service's `submitCredential` url to work with our wallet-proxy setup.
- Remove a "/".
- Bump the version.
=> Fix identity-provider-service url

.github/workflows/build-test-contracts-common.yaml, .github/workflows/build-test-sources.yaml, rust-bins/src/bin/keygen-genesis.rs, rust-bins/src/bin/keygen.rs, rust-bins/src/lib.rs, rust-src/ed25519_hd_key_derivation/src/lib.rs, rust-src/key_derivation/src/lib.rs
Fixes the warnings when running `cargo doc` and adds a lint to the Github actions.
Fixes a comment and adds the lint.
Note: `cargo doc` still throws warnings in `smart-contracts/wasm-chain-integration` when run without `--features display-state`. I wanted to add `#[cfg_attr(docsrs, cfg(feature = "display-state"))]`, but the `ptree` crate which is needed for compilation of the feature-gated function is only enabled when `display-state` is enabled.
=> Fix cargo doc warnings and add lints

.github/workflows/build-test-contracts-common.yaml, smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/schema_json.rs
When invoking `Display` on a `VersionedModuleSchema` with multiple contracts only the last contract was shown. This because contracts wasn’t appended to final output string in loop.
Also fix test since they didn’t run green. From the PR where they where added, and from this comment, https://github.com/Concordium/concordium-contracts-common/pull/99#discussion_r1250555893, I can see that at some time in the development the indention was set to 30. If I change the indention to 30 the test runs green. Hence I guess the test has been forgotten to run after the indention was changed from 30 -> 11.
- Changed loop to append contracts to final string
- Fix test which wasn’t running green.
=> Fix VersionedModuleSchema Display given multiple contracts

identity-provider-service/Cargo.lock, idiss/Cargo.lock, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, mobile_wallet/src/lib.rs, rust-bins/Cargo.lock, rust-bins/Cargo.toml, rust-bins/src/bin/trace_account.rs, rust-src/Cargo.lock, rust-src/concordium_base/Cargo.toml, rust-src/concordium_base/src/common/encryption.rs, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-test/Cargo.lock
concordium_base was using a pretty old version of base64 which then propagates through all dependencies, including the rust SDK, where users end up with duplicate dependency versions since base64 is so common.
Also update time and tungstenite since they have security advisories.
Note that there are some other duplicate dependencies but they are not simple to fix. This is just a quick and easy fix.
=> Update dependency to remove duplicate versions and address security advisories.

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Fix a bug in the serialization of the policies. The bug caused issues when using policies in your tests with the `concordium-smart-contract-testing` library.
Also marks some methods as const so they can be used to make constants.
- Serialize the number of policies using two bytes rather than one, which matches what the node does.
- Mark `Timestamp::from_timestamp_millis` and `Timestamp::timestamp_millis` as const
=> Fix policy serialization and mark methods as `const`

smart-contracts/contracts-common/concordium-contracts-common-derive/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common-derive/src/attribute.rs, smart-contracts/contracts-common/concordium-contracts-common-derive/src/lib.rs
Replaced usage of traits in the suggestions and docs with concrete types.
See  https://github.com/Concordium/concordium-rust-smart-contracts/issues/338 for context.
- Replaced usage of traits in suggestion, such as `&impl HasHost<..>` with the concrete types: `&Host<..>`.
- Remove generics from init and receive methods in docs.
=> Replaced usage of traits in suggestions and docs with concrete types

rust-src/concordium_base/src/transactions.rs
It is common to wrap WalletAccount into an Arc or Rc to clone it. If a method then requires an `&impl ExactSizedTransactionSigner` and we have an `Arc<WalletAccount>` we have to do the ugly reborrow `&*signer` to get the correct type.
Implementing these traits means that we can just write &signer instead.
=> Add support for ergonomic use of Arc and Rc over signer.

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/smart_contracts.rs
Add `parse` helper method to `ContractEvent`
- Add the method
=> Add `parse` helper method to `ContractEvent`

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/schema.rs
To deserialize events one need to be able to extract the event schema from the module schema. This PR extend `VersionedModuleSchema` with a getter.
Extend `VersionedModuleSchema` with a getter to event schema.
- [] The code compiles without warnings.
=> Add getting event schema from module schema

.github/workflows/build-test-contracts-common.yaml, rust-src/concordium_base/src/hashes.rs, smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/hashes.rs, smart-contracts/wasm-chain-integration/CHANGELOG.md, smart-contracts/wasm-chain-integration/src/utils.rs
For the reproducible builds work we need to embed build information into the Wasm modules. This PR adds helpers for extract this information.
=> Add helpers to extract build information from Wasm modules.

identity-provider-service/Cargo.lock, idiss/Cargo.lock, mobile_wallet/Cargo.lock, rust-bins/Cargo.lock, rust-src/Cargo.lock, rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/Cargo.toml, rust-src/concordium_base/src/smart_contracts.rs
Helper functions for reading modules.
It is often necessary to read a versioned module from a file, both in deploy scripts and in tools we have. This simplifies the repetitive task.
=> Add helpers to WasmModule.

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/schema_json.rs, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Currently deserialization of an `Type` in `to_json` fails if a Timestamp is too far in future.  This is because it calls `to_string` which used implementation of `Display`. The possible error in this implementation is never catched which makes the program panic.
- Bugfix `Display` implementation on `Timestamp` such that an error isn’t returned. If parsing to RFC3339 fails then a u64 as string is returned.
- Updated `FromStr` on `Timestamp` to be able to parse u64 string. 
=> Fix `Display` on `Timestamp`

smart-contracts/contracts-common/concordium-contracts-common-derive/src/lib.rs
Noticed an error in the documentation for contract init macro.
=> [contracts-common] Fix documentation regarding generating error schema for `init`

concordium-base.cabal, haskell-bins/genesis/Genesis.hs, haskell-src/Concordium/Constants.hs, haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/P7.hs, haskell-src/Concordium/Types/Migration.hs, haskell-src/Concordium/Types/Parameters.hs, haskell-src/Concordium/Types/ProtocolVersion.hs, haskell-src/Concordium/Types/SeedState.hs, haskell-tests/Types/UpdatesSpec.hs
Add protocol version 7 boilerplate, at this point it should behave the same as P6.
Part of https://github.com/Concordium/concordium-node/issues/1066.
Should be merged after https://github.com/Concordium/concordium-grpc-api/pull/49.
See also https://github.com/Concordium/concordium-node/pull/1075.
=> Add protocol version 7 and genesis data

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/base.rs
Support validatorId in Rust baker credentials.
=> Support validatorId in Rust credentials.

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/lib.rs
It would be nice to re-export the type `ed25519_dalek::PublicKey` in the smart contract integration testing library so that the `ed25519_dalek` crate does not have to be added as a dev-dependency in smart contract projects.
Re-export `ed25519_dalek` crate.
=> Re-export ed25519_dalek crate

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/lib.rs, rust-src/concordium_base/src/transactions.rs
- Add `singleton` function to `accountAccessSructure` that generates the most basic `account access structure` with one public key at index 0 in both maps.
- Add `new` function to `accountAccessStructure` that given the indices, public_keys, and thresholds generates corresponding  `account access structure`.  
-  Add `singleton` function
- Add `new` function
Note: The PR contains the two line changes from https://github.com/Concordium/concordium-base/pull/477.
=> Add singleton account access structure

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/benches/encrypted_transfers_benchmarks.rs, rust-src/concordium_base/benches/multiexp_bench.rs, rust-src/concordium_base/src/curve_arithmetic/mod.rs
Avoid field operations since they can be slow.
While it does not appear to have a significant effect for the BLS curve, but still has non-trivial effect, it might matter more with other curves.
=> Improve the multiscalar multiplication precomputation step.

rust-src/Cargo.toml, rust-src/concordium_base/src/common/mod.rs, rust-src/concordium_base/src/common/serialize.rs, smart-contracts/contracts-common/Cargo.toml
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
Avoid some warnings with newer rust versions.
- Set explicit resolver
- Don't re-export modules which have no public definitions.
=> Avoid Rust warnings

mobile_wallet/CHANGELOG.md, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, rust-bins/CHANGELOG.md, rust-bins/Cargo.lock, rust-bins/Cargo.toml, rust-bins/src/bin/client.rs, rust-bins/src/bin/user_cli.rs, rust-src/Cargo.lock, rust-src/key_derivation/CHANGELOG.md, rust-src/key_derivation/Cargo.toml, rust-src/key_derivation/src/lib.rs
According to the documentation for BIP39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic) the mnemonic must encode entropy in multiples of 32 bits, and the allowed size is 128-256 bits. This corresponds to allowing for 12, 15, 18, 21 and 24 word mnemonics. The current implementation allowed for any type of input, but assumed it was always 24 words. This change updates it so that it restricts the input as described by the standard, and also adds the missing tests to cover the test vectors for 12 and 18 words. There are no "official" test vectors for 15 and 21, and therefore a single test has been added to ensure that those work.
Note that this is a breaking change to the interface, hence the major bump.
- Restrict number of words to be in `[12, 15, …
=> Validate mnemonic word length

rust-src/wallet_library/src/credential.rs
Move `attribute_randomness` and `credential_public_keys` out of common struct for credential deployment as they should be derived from the seed phrase when creating the transaction from seed.
- Moved `credential_public_keys` and `attribute_randomness` to the keys specific struct from the common struct.
- I have not bumped versions or updated CHANGELOG as this code is not in use yet.
=> Fix credential common input struct

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/common/types.rs, smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/schema.rs, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Closes #429 and closes #450.
- Unify `Timestamp` from `concordium_base` and `concordium_contracts_common` in `concordium_contracts_common`.
- Add `SchemaType` implementation for `&str`.
=> Unify Timestamp in base and contracts_common

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/smart_contracts.rs, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs, smart-contracts/wasm-chain-integration/CHANGELOG.md, smart-contracts/wasm-chain-integration/src/utils.rs
Closes #465.
This PR unifies `WasmVersion` in `concordium-base` and `wasm-chain-integration` into one type in `concordium-contracts-common`.
See also the PR updating `cargo-concordium` to use the unified type https://github.com/Concordium/concordium-smart-contract-tools/pull/151
- Removes `WasmVersion::read` in favor of `common::Deserial` in `concordium-base`.
=> Unify WasmVersion into concordium_contracts_common

rust-src/concordium_base/src/transactions.rs
Add convenience for transactionssigner interfaces so that spurious references do not cause errors.
=> Improve ergonomics of using the transaction signer.

rust-src/Cargo.lock, rust-src/wallet_library/CHANGELOG.md, rust-src/wallet_library/Cargo.toml, rust-src/wallet_library/src/credential.rs
To reduce serialization code duplication the code for serializing a new credential for signing and for submission to the node is added to `wallet_library`.
- Added methods for serializing the credential deployment details (that which must be serialized, hashed and signed) and the credential deployment payload (that which is sent as a raw payload to the node).
=> Credential deployment serialization

identity-provider-service/Cargo.lock, idiss/Cargo.lock, mobile_wallet/Cargo.lock, rust-bins/Cargo.lock, rust-src/Cargo.lock, rust-src/concordium_base/Cargo.toml, rust-src/concordium_base/src/aggregate_sig/ffi.rs, rust-src/concordium_base/src/aggregate_sig/mod.rs, rust-src/concordium_base/src/encrypted_transfers/ffi.rs, smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs, smart-contracts/wasm-chain-integration/Cargo.lock, smart-contracts/wasm-chain-integration/Cargo.toml, smart-contracts/wasm-test/Cargo.lock
Update bs58 and ed25519-zebra dependencies to avoid duplicate transitive dependencies after the ed25519-dalek upgrade.
- The zebra upgrade has no API changes, simply an upgrade of curve25519-dalek.
- The bs58 has a few API changes, the only one relevant for us is renaming into to onto.
- Use ChaCha20Rng instead of StdRng. In the update from 0.7 to 0.8 of rand the StdRng was changed from ChaCha20 to ChaCha12 leading to some test failures due to hardcoded constants.
=> Update bs58 and ed25519-zebra dependencies.

smart-contracts/contracts-common/concordium-contracts-common/src/schema.rs
Make public such that `VersionedSchemaError` can be matched in applications which depend on `concordium-contracts-common`.
Made `VersionedSchemaError ` public in `concordium-contracts-common`
=> Make VersionedSchemaError public in concordium-contracts-common

haskell-src/Concordium/MerkleProofs.hs, haskell-tests/ConcordiumTests/MerkleProofs.hs
Support the inclusion of the protocol version in the calculation of the block hash.
- Include the protocol version in the block hash schema.
- Update the test accordingly.
=> Include the protocol version in block hash Merkle proofs.

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/hashes.rs
Need this to make the `ModuleRef` procedural macro that embeds it as a constant.
=> Made `HashBytes::new()` a const function

smart-contracts/wasm-chain-integration/CHANGELOG.md, smart-contracts/wasm-chain-integration/benches/wasm.rs, smart-contracts/wasm-chain-integration/src/utils.rs, smart-contracts/wasm-chain-integration/src/v1/mod.rs
Extend the `TestHost` to allow unit tests to use the state-related host function calls.
Needed to do allow unit tests for the new `StateBTreeMap` and `StateBTreeSet` introduced in 
https://github.com/Concordium/concordium-rust-smart-contracts/pull/405 using cargo-concordium.
Related cargo-concordium PR: https://github.com/Concordium/concordium-smart-contract-tools/pull/158
- Define a new constructor for `TestHost` taking the instance state to make available.
- `TestHost` support host function calls related to state.
- `run_module_tests` provide an empty instance state for every test case.
=> Support state-related host calls in `TestHost`

README.md, Setup.hs, idiss/README.md
Support Rust version 1.73 on Windows. This changes how the Haskell code is linked to Rust code to use dynamic linking (instead of static, as previously) on Windows.
- The build process no longer copies static libraries to the `lib` directory, and removes them if they are present.
- The DLLs are copied to the install directory in the post-copy build hook. This ensures that they are in the path when `stack` runs binaries
=> Support Rust 1.73 on Windows.

haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/ProtocolVersion.hs, haskell-tests/Generators.hs, haskell-tests/Types/PayloadSerializationSpec.hs
Disable encrypted transfers in protocol version 7. This disallows the deserialization of payload types `TransferToEncrypted`, `EncryptedAmountTransfer` and `EncryptedAmountTransferWithMemo` in P7. (`TransferToPublic` is unaffected.)
- Introduce `supportsEncryptedTransfers` predicate that indicates which protocol versions support encrypted transfers (P6 and earlier).
- Condition deserialization of the relevant payload types on encrypted transfers being supported.
- Update and bolster serialization tests.
- `decodePayload` no longer takes the payload size as a separate parameter, since in practice it is always the size of the payload.
=> Disable encrypted transfers in P7.

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Deriving default is useful and convenient, especially for a small type such as this.
Simply derives Default on `Amount`.
=> Derive default on Amount

rust-src/Cargo.lock, rust-src/wallet_library/CHANGELOG.md, rust-src/wallet_library/Cargo.toml, rust-src/wallet_library/src/default_wallet_config.rs
To add the newly introduced company attribute "legalCountry" to the list of allowed attributes for set membership proofs in the wallet library. Closes #541.
The above mentioned attribute is now among the allowed ones.
=> Add legal country to allowed attributes in wallet-library.

concordium-base.cabal, haskell-bins/genesis/Genesis.hs, haskell-src/Concordium/Constants.hs, haskell-src/Concordium/Cost.hs, haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/P8.hs, haskell-src/Concordium/Genesis/Parameters.hs, haskell-src/Concordium/Types/Accounts.hs, haskell-src/Concordium/Types/Migration.hs, haskell-src/Concordium/Types/Parameters.hs, haskell-src/Concordium/Types/ProtocolVersion.hs, haskell-src/Concordium/Types/Queries.hs, haskell-src/Concordium/Types/SeedState.hs, haskell-src/Concordium/Types/UpdateQueues.hs, haskell-src/Concordium/Wasm.hs, haskell-tests/Generators.hs, haskell-tests/Genesis/ParametersSpec.hs, haskell-tests/Types/ParametersSpec.hs, haskell-tests/Types/PayloadSerializationSpec.hs, haskell-tests/Types/TransactionSummarySpec.hs, haskell-tests/Types/UpdatesSpec.hs
This adds the boilerplate code for protocol version 8. Note that there is no difference currently between protocol version 7 and 8. We need a new account version, as well as a new chain parameters version to incorporate the planned changes for the suspension of inactive validators coming in protocol version 8.
Boilerplate and tests are added for a new protocol version, account version and chain parameter version.
=> Protocol version 8 boilerplate

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Accounts.hs
This adds the `AccountIsSuspended` flag to the `AccountInfo` to signal when a account has been suspended. This is central to the suspended validator project NOD-599.
=> `AccountIsSuspended` flag for `AccountInfo`

smart-contracts/contracts-common/concordium-contracts-common/CHANGELOG.md, smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Add conversion from `&[u8]` to `AccountAddress` to simplify constructing the type when reading byte values from a database.
Add conversion from `&[u8]` to `AccountAddress`.
=> Add conversion helper

.github/workflows/build-test-contracts-common.yaml, .github/workflows/build-test-smart-contracts.yaml, .github/workflows/build-test-sources.yaml, haskell-src/Concordium/GRPC2.hs
The changes to cooldown behaviour now allow an account to transition directly from delegator to baker and vice-versa. In these cases, an additional event is generated in the configure baker/delegator transaction to indicate that the delegator/baker has been removed.
- GRPC support for removing baker/delegator as part of configuring delegator/baker.
=> GRPC support for missing events for baker/delegator configure transactions

haskell-src/Concordium/Types/ProtocolVersion.hs
This adds a guard for protocol versions supporting account suspension.
=> Protocol 8: guard for p8 support

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Accounts.hs, haskell-src/Concordium/Types/Execution.hs, haskell-tests/Generators.hs, haskell-tests/Types/PayloadSerializationSpec.hs, mobile_wallet/src/lib.rs, rust-src/concordium_base/src/transactions.rs
This implements the new suspend/resume field and events for the `ConfigureBaker` transaction in base.
=> Suspend in ConfigureBaker

haskell-src/Concordium/Types/Accounts.hs, haskell-src/Concordium/Types/Conditionally.hs, haskell-src/Concordium/Types/ProtocolVersion.hs
We add the `bieAccountIsSuspended` field to `BakerInfoEx` to make the field persistent together with the account. There are also a few new types/constraints that are useful for the implementation in the consensus.
Add the suspended field to the persisted fields of the validator account.
See above.
=> Add `bieAccountIsSuspended` field to `BakerInfoEx`

mobile_wallet/CHANGELOG.md, mobile_wallet/Cargo.lock, mobile_wallet/Cargo.toml, mobile_wallet/src/lib.rs
Not-enforcing padding of the base64 schema when signing a binary message in the CryptoX wallets.
In the past, some tools added and/or required padding on the schema in the Concordium ecosystem while others did not. At some point, we relaxed it and removed that requirement:
https://github.com/Concordium/concordium-dapp-libraries/pull/63/files
Currently,
- `cargo-concordium` does not add padding
- `browser wallet` does not enforce padding
- `dapp-libraries` does not enforce padding
Padding means that there are zero, one, or two `=` characters added at the end of the base64 string representing the schema to make it dividable.
The mobile wallets still enforce padding which was incompatible with the schema produced by `cargo-concordium`.
- Remove check on padding in mobile wallets library
=> Remove check on padding in mobile wallets library

concordium-base.cabal, haskell-src/Concordium/Wasm.hs, haskell-tests/Spec.hs, haskell-tests/Types/ValidName.hs, smart-contracts/contracts-common/concordium-contracts-common/src/types.rs
Fix the consistency of how contract init, receive and entrypoint names are handled between Haskell and Rust.
- Broaden what is accepted in Haskell to match what is accepted in Rust.
- Additional test in Rust and Haskell.
=> Fix the consistency of name validity between Haskell and Rust.

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Accounts.hs
This moves the suspended flag from `AccountInfo` to `AccountStakingInfo.Baker`. This also needs a change in `concordium-grpc-api` that needs to go in first: https://github.com/Concordium/concordium-grpc-api/pull/63.
We move the suspended flag one level down to the `AccountStakingInfo` to reflect that it is a property of a validator and not the account.
see above.
=> p8: Move the suspended flag

Setup.hs
The static build of the node uses the "dynamic linking" mode for building `concordium-base`, but requires that the rust library is also statically built. This was changed as a result of #559, so here we bring it back.
- Build the rust libraries as both `cdylib` and `staticlib` in the dynamic Linux build process.
=> Fix static node build

concordium-base.cabal, haskell-src/Concordium/Common/Time.hs, haskell-tests/Spec.hs, haskell-tests/Types/TimestampSpec.hs
Allow JSON deserializing `Timestamp` in Haskell from the format produced by the [Rust serialization](https://github.com/Concordium/concordium-base/blob/58f871e57ab8543ae499d3cccc14ff7ce7b4842a/smart-contracts/contracts-common/concordium-contracts-common/src/types.rs#L873). The divergence was introduced as a consequence of https://github.com/Concordium/concordium-base/pull/499/files, which unified two previously distinct Rust `Timestamp` implementations. The JSON serialization is in particular used by the transaction logger when ScheduleTransfer transactions are logged in the wallet proxy database. This change allows the wallet proxy to parse the String-formatted timestamps.
- New `FromJSON` implementation for `Timestamp`.
- Testing
=> Support timestamp JSON deserialization from strings.

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/InvokeContract.hs, haskell-src/Concordium/Types/Queries.hs, haskell-tests/Generators.hs
Issue: https://github.com/Concordium/concordium-node/issues/1262
Related: https://github.com/Concordium/concordium-grpc-api/pull/68 and https://github.com/Concordium/concordium-node/pull/1261
Supplement `ContractInitialized` events with the initialization parameter for the purposes of queries. This is to support queries that get transaction events returning contract initialization parameters.
Note that we do not change the data that makes up the transaction outcome for the purposes of consensus. That is, the events as stored in the block state and hashed to compute the block hash do not include the contract initialization parameter. Instead, the parameter is added in response to queries from the original transaction data.
- A number of types are augmented or replaced with "supplemented" …
=> Add parameter to `ContractInitialized` events

haskell-src/Concordium/Types/Queries.hs
Required for: https://github.com/Concordium/concordium-client/pull/332
Add `ToJSON` instance for `AccountPending`, which is used by the raw `GetScheduledReleaseAccounts` and `GetCooldownAccounts` commands in `concordium-client`.
- Add `ToJSON` instance.
=> ToJSON instance for AccountPending.

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Genesis/Data/Base.hs, haskell-src/Concordium/Genesis/Parameters.hs, haskell-src/Concordium/Types/Migration.hs, haskell-src/Concordium/Types/Parameters.hs, haskell-src/Concordium/Types/Queries.hs, haskell-src/Concordium/Types/Transactions.hs, haskell-src/Concordium/Types/UpdateQueues.hs, haskell-src/Concordium/Types/Updates.hs, haskell-tests/Generators.hs, rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/updates.rs
Add validator score parameters to chain parameters. The grpc changes need to go in first (https://github.com/Concordium/concordium-grpc-api/pull/66)
This adds new parameters for validator suspension and all the necessary boilerplate code.
=> Validator score chain parameters

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Genesis/Parameters.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/Parameters.hs, haskell-src/Concordium/Types/Transactions.hs, haskell-tests/Generators.hs, haskell-tests/Types/TimestampSpec.hs
Add the account address to `BakerSuspended` and `BakerResumed` transaction outcomes, and to `ValidatorSuspended` and `ValidatorPrimedForSuspension` special outcomes.
- Fix: encode `ValidatorPrimedForSuspension` at the correct message type in the protobuf encoding.
- Add the account address fields to `ValidatorSuspended` and `ValidatorPrimedForSuspension`.
- Update the GRPC protobuf encoding to include the account address
- Update the binary serialization and deserialization of the events.
- Add the account address fields to `BakerSuspended` and `BakerResumed`
- Update the binary serialization and deserialization of the events.
- Update the JSON serialization and deserialization of the events.
- Update test generators
- Fix: remove test focus on timestamp serialization.
hard-to-understand …
=> Add account address to transaction outcomes and special events.

haskell-src/Concordium/Genesis/Data.hs, haskell-src/Concordium/Genesis/Data/P8.hs, haskell-src/Concordium/Types/Migration.hs
Implementation of chain parameter migration for P7 -> P8.
Fixes #544.
Fixes #545.
=> implementation of chain parameters migration

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Queries.hs
Add suspension info to `PoolCurrentPaydayInfo` /  `PoolInfoResponse`. This depends on https://github.com/Concordium/concordium-grpc-api/pull/74.
See above.
=> Extension of PoolCurrentPaydayInfo/PoolInfoResponse

rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/updates.rs
Changes to support the genesis tool in protocol version 8.
- Add `ChainParametersVersion3` with appropriate `impl`s.
- `camelCase` for serde `ValidatorScoreParameters` for consistency.
=> Rust support for new chain parameters version.

haskell-src/Concordium/GRPC2.hs
Related issue: https://github.com/Concordium/concordium-node/issues/1312
Ensure `ChainParmetersV3` is correctly serialized in protobuf.
- Use `v3` instead of `v2`.
- Include the `validatorScoreParameters`.
=> Serialize to the correct chain parameters version.

haskell-src/Concordium/Types/Transactions.hs
Linked: https://github.com/Concordium/concordium-client/pull/338 https://github.com/Concordium/concordium-wallet-proxy/pull/119
Fix JSON serialization of `SpeicalTransacationOutcome`. This is needed for the wallet proxy.
- Use `dropWhile isLower` instead of `drop 3` to account for the new constructors having different prefixes.
=> Fix JSON serialization of SpeicalTransacationOutcome

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/Cargo.toml
Release `concordium_base` 7.0.0
=> Bump version and release concordium_base.

.github/workflows/build-test-sources.yaml
Update the version of the cache action used in the build workflow since v2 has been deprecated.
- Update `actions/cache@v2` to `actions/cache@v4`
=> Update the cache version in github actions.

haskell-src/Concordium/Types/ProtocolVersion.hs
This commit introduces type-level constraints to ensure functions and fields can only be used with protocol and account versions that support Protocol Level Tokens (PLTs).
=> plt: type level constraints for PLT support

concordium-base.cabal, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs, haskell-src/Concordium/Types/Queries/Tokens.hs, haskell-src/Concordium/Types/Tokens.hs, haskell-tests/Spec.hs, haskell-tests/Types/CBOR.hs, package.yaml
Part of NOD-682
This implements CBOR encoding and decoding for the `TokenInitializationParameter` in line with the CDDL specification (https://github.com/Concordium/concordium-base/pull/607). The decoding is permissive (though it does not allow spurious additional map keys, etc.) and the encoding follows deterministic CBOR.
- Add `cborg` package dependency.
- Helpers for decoding and encoding types as CBOR maps.
- Encoding and decoding of 'TokenAmount'.
- Encoding and decoding of 'TokenInitializationParameters'.
- Unit tests.
- JSON serialization for `TokenInitializationParameters` and `TokenAmount`.
- Modify the JSON serialization of `CreatePLT` to allow the `initializationParameters` to be given either as a hex-encoded byte string or as JSON-encoded `TokenInitializationParameters`. …
=> CBOR (de)serialization for token initialization parameter

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs, haskell-src/Concordium/Types/Tokens.hs, haskell-src/Concordium/Types/Updates.hs, haskell-tests/Types/UpdatesSpec.hs
Part of [COR-698](https://linear.app/concordium/issue/COR-698/token-module-basic-plt-initialization)
Depends on: https://github.com/Concordium/concordium-grpc-api/pull/90
Required for: https://github.com/Concordium/concordium-node/pull/1370
- `TokenModuleRejectReason` type for failures generated by the token module.
- `RejectReason` cases: `TokenExists`, `TokenModuleInvalid`, `TokenModuleInitializeFailed`
- New `ToProto` instances.
- Support PLT creation in `convertUpdatePayload`.
- Support PLT creation failure in `ToProto SupplementedTransactionSummary`.
- Tweak the authorized keys for PLT creation to always be (just) the first one. 
=> PLT initialization

concordium-base.cabal, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Memo.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs, haskell-tests/Types/CBOR.hs
Part of COR-677
This defines the CBOR encoding and decoding of token-holder transactions.
- Refactor `Memo` to a separate module to avoid cyclic dependencies.
- Slight refactoring of `decodeMap` to allow reuse of helpers for sequences.
- Define types, decoders and encoders related to token-holder transactions.
=> CBOR encoding of token-holder transactions

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types/Queries.hs
Ref COR-1344.
Related PR for grpc: https://github.com/Concordium/concordium-grpc-api/pull/91
Related PR for node: https://github.com/Concordium/concordium-node/pull/1376
- Moved `updateQueuesNextSequenceNumbers` concordium-node repo and made it inline.
=> Expose the update sequence number for PLTs

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs
Part of COR-683
Depends on https://github.com/Concordium/concordium-grpc-api/pull/92
Required by https://github.com/Concordium/concordium-node/pull/1379
This PR supports the implementation of token-holder transactions in the Token Module. In particular, it adds reject reasons (with CBOR-coding) for token-holder transactions. (These are not yet schematised in CDDL, and could easily change, so are provisional for now.)
- `tokenHolderTransactionFromBytes` and `tokenHolderTransactionToBytes` - convenience functions required by the token module implementation.
- `EncodedTokenRejectReason` - a pair of a `type` indicator and optional CBOR-encoded details.
- `TokenHolderFailure` - a sum type for failure reasons that can be generated by the token-holder transaction.
- Encoding and decoding …
=> PLT Reject Reasons CBOR

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/base.rs, rust-src/concordium_base/src/lib.rs, rust-src/concordium_base/src/protocol_level_tokens/cbor.rs, rust-src/concordium_base/src/protocol_level_tokens/mod.rs, rust-src/concordium_base/src/protocol_level_tokens/token_amount.rs, rust-src/concordium_base/src/protocol_level_tokens/token_event.rs, rust-src/concordium_base/src/protocol_level_tokens/token_id.rs, rust-src/concordium_base/src/protocol_level_tokens/token_module_ref.rs, rust-src/concordium_base/src/transactions.rs, rust-src/concordium_base/src/updates.rs
Ref COR-1146.
Introduce basic types for plt in `rust-src/concordium-base`
Relevant PR in rust-sdk: https://github.com/Concordium/concordium-rust-sdk/pull/240 and https://github.com/Concordium/concordium-rust-sdk/pull/243 and https://github.com/Concordium/concordium-rust-sdk/pull/246
=> Base support for P9 in concordium_base rust crate

cbor-schema/plt.cddl, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs, haskell-tests/Types/CBOR.hs
Part of COR-1371
Required by https://github.com/Concordium/concordium-node/pull/1385
This defines a CDDL schema for representing token module state, and implements encoding and decoding CBOR from a Haskell type.
- Add `token-module-state` to the CDDL schema.
- Define type `TokenModuleState` with CBOR encoding and decoding following the schema.
- Add tests.
=> CBOR and schema for token module state.

scripts/identity-provider-service.Dockerfile
Change base images from Ubuntu 20.04 to 24.04 since. The former is deprecated https://github.com/actions/runner-images/issues/11101
Changed relevant base images
=> upgrade ubuntu base image

haskell-src/Concordium/GRPC2.hs, haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/Execution.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs, haskell-tests/Generators.hs, haskell-tests/Types/CBOR.hs, rust-src/concordium_base/src/protocol_level_tokens/token_event.rs, rust-src/concordium_base/src/protocol_level_tokens/token_holder.rs, rust-src/concordium_base/src/protocol_level_tokens/token_operations.rs, rust-src/concordium_base/src/protocol_level_tokens/token_reject_reason.rs, rust-src/concordium_base/src/updates.rs
We want to ensure the Protocol-level token (PLT) events (transfer, mint and burn) are structured in a forward-compatible way, such that we can expand the events in the future, with minimal breakage in the ecosystem. Specifically adding new token holder entities as there are already discussions on adding smart contract support. Here we need to consider the additional context as well, since memos might not be relevant for smart contracts, but instead a receive-hook name with some parsed input parameters would be needed in the events.
https://linear.app/concordium/issue/COR-1506/align-json-serialization-of-plt-events-across-rusthaskell-and-adhere
Related PRs:
https://github.com/Concordium/concordium-client/pull/382
https://github.com/Concordium/concordium-node/pull/1402 …
=> Use extendable tokenHolder types in plt events (COR-1506)

rust-src/concordium_base/src/protocol_level_tokens/token_reject_reason.rs
Related to:
https://github.com/Concordium/concordium-rust-sdk/pull/277
PLT transactions with reject reasons are not aligned in their JSON serialization. In case a user generated a plt transaction that rejects (unhappy path), this leads to that the historical transaction history cannot be parsed correctly in the `wallet-proxy` and cannot be displayed in the wallet for that user. Fix serializations issues in rejected plt transactions.
=> Small json serialization fix (COR 1536)

cbor-schema/plt.cddl
Adds the `token-pause` along with a corresponding field on `token-module-state` operation to `plt.cddl`.
One important thing to note here, is that I did not include a reject reason specifically for this. My thought is that it would be fine to use the existing "reject-details-unsupported-operation" for this based on the assumption that it is not intended only for signalling operations being **permanently unsupported**.
=> Add token-pause operation to plt.cddl

cbor-schema/plt.cddl
A revised token-pause type declaration based on https://github.com/Concordium/concordium-base/pull/692#pullrequestreview-2983765665
- Changes token-(un)pause to be separate operations
- Allows for future extensibility in the associated token module state
- Allows for future extensibility in associated token-(un)pause events.
=> Revise token pause cddl types

haskell-src/Concordium/Types.hs, haskell-src/Concordium/Types/ProtocolLevelTokens/CBOR.hs
https://linear.app/concordium/issue/COR-1384/improve-cbor-decoding-of-plt-events
concordium-client PR: https://github.com/Concordium/concordium-client/pull/395
Add function for decoding reject reason details fro mthe token module reject reason.
=> Add function for decoding the token module reject reason details

rust-src/concordium_base/CHANGELOG.md, rust-src/concordium_base/src/id/types.rs
Adding `#[derive(Clone)]` for `AccountCredentialWithoutProofs` for the unit tests of the `TokenClient's`  `validate_transfer` method.
- Added `#[derive(Clone)]` for `AccountCredentialWithoutProofs`
=> COR-1665 Token client validate transfer test

rust-src/concordium_base/src/common/cbor.rs, rust-src/concordium_base/src/common/cbor/decoder.rs, rust-src/concordium_base/src/common/mod.rs, rust-src/concordium_base/src/common/upward.rs, rust-src/concordium_base/src/protocol_level_tokens/token_event.rs, rust-src/concordium_base/src/protocol_level_tokens/token_operations.rs, rust-src/concordium_base/src/protocol_level_tokens/token_reject_reason.rs, rust-src/concordium_base/src/transactions.rs, rust-src/concordium_base_derive/src/cbor.rs
Closes the parts of https://linear.app/concordium/issue/COR-1791/use-upward-maybeknown-construct-in-rust-cbor that are needed in concordium-base.
=> Use Upward construct in Rust CBOR
